// APETATO weapons — EXOTIC.
// Pets, boomerangs, honey traps and things the shop keeps behind the counter.
// Pure frozen data. Interpreted by src/game systems; no logic lives here.

function deepFreeze(obj) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (v && typeof v === 'object') deepFreeze(v);
  }
  return Object.freeze(obj);
}

export const EXOTIC_WEAPONS = deepFreeze([
  {
    id: 'banana_boomerang',
    name: 'Banana Boomerang',
    description: 'The only fruit with a return policy. Hits twice, apologizes never.',
    classes: ['ranged'],
    tier: 1,
    basePrice: 15,
    stats: { damage: 4, cooldown: 1.0, range: 8, knockback: 3, critChance: 4, critMult: 1.5, projectileSpeed: 12, pierce: 3 },
    scaling: { rangedDamage: 1.0, projectileSpeed: 0.3 },
    behavior: 'boomerang',
    behaviorParams: { returnDamageMult: 1.0, spinVisual: true },
    onHit: [],
    visual: {
      projectile: 'spin_banana',
      muzzle: 'yellow_flash',
      model: {
        base: 'custom', scale: 0.5, primary: '#ffd93b', secondary: '#8a5a2b', accent: '#6b4a1f',
        parts: [
          { shape: 'box', size: [0.28, 0.04, 0.08], pos: [0, 0, 0], rot: [0, 0.6, 0], color: 'primary' },
          { shape: 'box', size: [0.08, 0.04, 0.24], pos: [0.1, 0, 0.1], rot: [0, 0.6, 0], color: 'primary' },
          { shape: 'sphere', size: [0.04, 0.04, 0.04], pos: [-0.12, 0, -0.04], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'spin',
      },
    },
    sfx: 'whirr',
    unlock: { type: 'default' },
  },
  {
    id: 'pocket_chimp',
    name: 'Pocket Chimp',
    description: 'A very small colleague. Paid entirely in raisins and revenge.',
    classes: ['pet'],
    tier: 1,
    basePrice: 16,
    stats: { damage: 4, cooldown: 0.9, range: 6, knockback: 1, critChance: 3, critMult: 1.5, count: 1, duration: 0 },
    scaling: { damagePct: 0.8, engineering: 0.4 },
    behavior: 'pet',
    behaviorParams: { petSpeed: 7, petHp: 20, attackType: 'melee', respawn: 5 },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'poof',
      model: {
        base: 'custom', scale: 0.45, primary: '#7a5233', secondary: '#d9b38c', accent: '#2b2b2b',
        parts: [
          { shape: 'sphere', size: [0.14, 0.14, 0.12], pos: [0, 0.05, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.08, 0.08, 0.06], pos: [0, 0.02, 0.09], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'torus', size: [0.05, 0.015, 0.05], pos: [0, 0.18, 0], rot: [1.2, 0, 0], color: 'accent' },
        ],
        animation: 'hop',
      },
    },
    sfx: 'chitter',
    unlock: { type: 'default' },
  },
  {
    id: 'attack_parrot',
    name: 'Attack Parrot',
    description: 'Repeats everything you say, then dive-bombs whoever disagrees.',
    classes: ['pet'],
    tier: 2,
    basePrice: 30,
    stats: { damage: 6, cooldown: 0.8, range: 9, knockback: 2, critChance: 4, critMult: 1.5, count: 1, duration: 0 },
    scaling: { damagePct: 0.9, attackSpeed: 0.3 },
    behavior: 'pet',
    behaviorParams: { petSpeed: 10, petHp: 15, attackType: 'dive', flying: true, respawn: 5 },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'feather_puff',
      model: {
        base: 'custom', scale: 0.45, primary: '#d9302b', secondary: '#3fa7d6', accent: '#ffd93b',
        parts: [
          { shape: 'sphere', size: [0.12, 0.14, 0.16], pos: [0, 0.05, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'cone', size: [0.04, 0.1, 0.04], pos: [0, 0.05, 0.14], rot: [1.3, 0, 0], color: 'accent' },
          { shape: 'box', size: [0.04, 0.1, 0.14], pos: [0.1, 0.05, -0.02], rot: [0, 0, -0.5], color: 'secondary' },
          { shape: 'box', size: [0.04, 0.1, 0.14], pos: [-0.1, 0.05, -0.02], rot: [0, 0, 0.5], color: 'secondary' },
        ],
        animation: 'hover',
      },
    },
    sfx: 'squawk',
    unlock: { type: 'default' },
  },
  {
    id: 'honey_trap',
    name: 'Honey Trap',
    description: 'A puddle of weapons-grade honey. Sweet, sticky, deeply unfair.',
    classes: ['tech', 'chaos'],
    tier: 2,
    basePrice: 26,
    stats: { damage: 5, cooldown: 1.6, range: 6, knockback: 0, critChance: 3, critMult: 1.5, radius: 2.4, duration: 4 },
    scaling: { engineering: 0.8, effectDuration: 0.6 },
    behavior: 'mine',
    behaviorParams: { armTime: 0.3, maxActive: 3, triggerRadius: 1.5, stickyPatch: true },
    onHit: [
      { trigger: 'onHit', chance: 100, do: [{ op: 'status', status: 'slow', dps: 1, duration: 3, target: 'area', radius: 2.4 }] },
    ],
    visual: {
      projectile: 'honey_glob',
      muzzle: 'toss_puff',
      model: {
        base: 'custom', scale: 0.5, primary: '#ffb52e', secondary: '#c9861d', accent: '#fff2b0',
        parts: [
          { shape: 'cylinder', size: [0.16, 0.05, 0.16], pos: [0, -0.05, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.08, 0.06, 0.08], pos: [0.05, 0.0, 0.03], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'sphere', size: [0.04, 0.05, 0.04], pos: [-0.07, 0.0, -0.04], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'squelch',
    unlock: { type: 'default' },
  },
  {
    id: 'orbiting_banana_moons',
    name: 'Orbiting Banana Moons',
    description: 'Four crescent bananas in stable orbit. NASA calls weekly. We do not answer.',
    classes: ['magic', 'speed'],
    tier: 2,
    basePrice: 32,
    stats: { damage: 4, cooldown: 0.4, range: 3.2, knockback: 3, critChance: 3, critMult: 1.5, count: 4, radius: 3.2 },
    scaling: { elementalDamage: 0.8, attackSpeed: 0.4 },
    behavior: 'orbit',
    behaviorParams: { orbitSpeed: 4.5, eccentric: true },
    onHit: [],
    visual: {
      projectile: 'crescent_moon',
      muzzle: 'sparkle',
      model: {
        base: 'custom', scale: 0.5, primary: '#ffd93b', secondary: '#dfe6ff', accent: '#b04aff',
        parts: [
          { shape: 'torus', size: [0.2, 0.02, 0.2], pos: [0, 0, 0], rot: [1.57, 0, 0], color: 'secondary' },
          { shape: 'sphere', size: [0.07, 0.07, 0.07], pos: [0.2, 0, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.07, 0.07, 0.07], pos: [-0.2, 0, 0], rot: [0, 0, 0], color: 'primary' },
        ],
        animation: 'spin',
      },
    },
    sfx: 'hum',
    unlock: { type: 'default' },
  },
  {
    id: 'schrodingers_crate',
    name: 'Schrödinger\'s Crate',
    description: 'Until it lands, it contains every weapon. Then it commits to one, loudly.',
    classes: ['chaos'],
    tier: 2,
    basePrice: 28,
    stats: { damage: 8, cooldown: 1.2, range: 8, knockback: 4, critChance: 3, critMult: 1.5, projectileSpeed: 10, radius: 2 },
    scaling: { luck: 0.8, damagePct: 0.8 },
    behavior: 'chaos_random',
    behaviorParams: {
      pool: ['projectile', 'lobbed', 'nova', 'chain', 'boomerang'],
      damageJitter: 0.5,
    },
    onHit: [],
    visual: {
      projectile: 'mystery_crate',
      muzzle: 'confetti_pop',
      model: {
        base: 'custom', scale: 0.5, primary: '#8a5a2b', secondary: '#ffd93b', accent: '#b04aff',
        parts: [
          { shape: 'box', size: [0.2, 0.2, 0.2], pos: [0, 0, 0], rot: [0, 0.4, 0], color: 'primary' },
          { shape: 'box', size: [0.22, 0.05, 0.05], pos: [0, 0, 0], rot: [0, 0.4, 0], color: 'secondary' },
          { shape: 'sphere', size: [0.05, 0.05, 0.05], pos: [0, 0.14, 0], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'bob',
      },
    },
    sfx: 'mystery_pop',
    unlock: { type: 'default' },
  },
  {
    id: 'baby_gorilla_buddy',
    name: 'Baby Gorilla Buddy',
    description: 'Small today, load-bearing tomorrow. Currently practicing chest thumps on shins.',
    classes: ['pet', 'melee'],
    tier: 3,
    basePrice: 54,
    stats: { damage: 12, cooldown: 1.0, range: 5, knockback: 6, critChance: 3, critMult: 1.5, count: 1, duration: 0 },
    scaling: { damagePct: 1.0, meleeDamage: 0.5, maxHp: 0.2 },
    behavior: 'pet',
    behaviorParams: { petSpeed: 6, petHp: 45, attackType: 'smash', taunt: true, respawn: 6 },
    onHit: [
      { trigger: 'onHit', chance: 15, do: [{ op: 'status', status: 'stun', dps: 0, duration: 0.5, target: 'target' }] },
    ],
    visual: {
      projectile: 'none',
      muzzle: 'impact_dust',
      model: {
        base: 'custom', scale: 0.55, primary: '#3a3a3a', secondary: '#8f9aa3', accent: '#d9b38c',
        parts: [
          { shape: 'sphere', size: [0.18, 0.16, 0.15], pos: [0, 0.05, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.1, 0.08, 0.07], pos: [0, 0.0, 0.12], rot: [0, 0, 0], color: 'accent' },
          { shape: 'box', size: [0.06, 0.12, 0.06], pos: [0.14, -0.05, 0], rot: [0, 0, -0.2], color: 'primary' },
          { shape: 'box', size: [0.06, 0.12, 0.06], pos: [-0.14, -0.05, 0], rot: [0, 0, 0.2], color: 'primary' },
        ],
        animation: 'hop',
      },
    },
    sfx: 'baby_roar',
    unlock: { type: 'default' },
  },
  {
    id: 'chaos_barrel_organ',
    name: 'Chaos Barrel Organ',
    description: 'Crank the handle, roll the dice. Music critics rate it "run".',
    classes: ['chaos'],
    tier: 3,
    basePrice: 50,
    stats: { damage: 11, cooldown: 0.9, range: 9, knockback: 3, critChance: 3, critMult: 1.5, projectileSpeed: 12, count: 2, radius: 2 },
    scaling: { luck: 1.0, damagePct: 0.9 },
    behavior: 'chaos_random',
    behaviorParams: {
      pool: ['projectile', 'burst', 'shotgun', 'chain', 'nova', 'homing'],
      damageJitter: 0.7,
      jackpotChance: 5,
      jackpotMult: 4,
    },
    onHit: [],
    visual: {
      projectile: 'music_note',
      muzzle: 'confetti_pop',
      model: {
        base: 'custom', scale: 0.6, primary: '#7a4a8a', secondary: '#ffd93b', accent: '#d9302b',
        parts: [
          { shape: 'box', size: [0.24, 0.2, 0.16], pos: [0, 0, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'cylinder', size: [0.03, 0.12, 0.03], pos: [0.16, 0.08, 0], rot: [0, 0, -1.2], color: 'secondary' },
          { shape: 'cylinder', size: [0.02, 0.08, 0.02], pos: [-0.06, 0.16, 0], rot: [0, 0, 0], color: 'accent' },
          { shape: 'cylinder', size: [0.02, 0.11, 0.02], pos: [0.02, 0.17, 0], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'bob',
      },
    },
    sfx: 'kazoo_chord',
    unlock: { type: 'default' },
  },
  {
    id: 'spirit_orangutan',
    name: 'Spirit Orangutan',
    description: 'The ghost of an elder who never finished his last banana. He fights, you feast.',
    classes: ['pet', 'lifesteal'],
    tier: 4,
    basePrice: 100,
    stats: { damage: 18, cooldown: 0.9, range: 7, knockback: 5, critChance: 3, critMult: 1.5, count: 1, duration: 0 },
    scaling: { damagePct: 1.1, elementalDamage: 0.5, lifesteal: 0.4 },
    behavior: 'pet',
    behaviorParams: { petSpeed: 8, petHp: 999, ethereal: true, attackType: 'haunt', respawn: 2 },
    onHit: [
      { trigger: 'onHit', chance: 40, do: [{ op: 'heal', amount: 1 }] },
      { trigger: 'onKill', chance: 25, do: [{ op: 'heal', amount: 2 }] },
    ],
    visual: {
      projectile: 'spirit_wisp',
      muzzle: 'shadow_puff',
      model: {
        base: 'custom', scale: 0.6, primary: '#b8e0e8', secondary: '#7ec8e3', accent: '#fff2b0',
        parts: [
          { shape: 'sphere', size: [0.18, 0.18, 0.15], pos: [0, 0.1, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.1, 0.09, 0.07], pos: [0, 0.06, 0.13], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'cone', size: [0.12, 0.2, 0.12], pos: [0, -0.12, 0], rot: [3.14, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.04, 0.04, 0.04], pos: [0, 0.3, 0], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'hover',
      },
    },
    sfx: 'ghost_hoot',
    unlock: { type: 'wins', count: 5 },
  },
  {
    id: 'drummer_lemur',
    name: 'Drummer Lemur',
    description: 'Keeps a beat on enemy skulls. The rhythm section fights back.',
    classes: ['pet', 'support'],
    tier: 2,
    basePrice: 29,
    stats: { damage: 7, cooldown: 0.8, range: 6, knockback: 2, critChance: 3, critMult: 1.5, count: 1, duration: 0 },
    scaling: { engineering: 0.5, attackSpeed: 0.3 },
    behavior: 'pet',
    behaviorParams: { petSpeed: 8, petHp: 18, attackType: 'melee', respawn: 5 },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'drum_ring',
      model: {
        base: 'custom', scale: 0.45, primary: '#8f9aa3', secondary: '#2b2b2b', accent: '#d9534f',
        parts: [
          { shape: 'sphere', size: [0.12, 0.13, 0.11], pos: [0, 0.06, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'cylinder', size: [0.09, 0.06, 0.09], pos: [0, -0.04, 0.08], rot: [0, 0, 0], color: 'accent' },
          { shape: 'torus', size: [0.05, 0.015, 0.05], pos: [0, 0.17, 0], rot: [1.2, 0, 0], color: 'secondary' },
        ],
        animation: 'hop',
      },
    },
    sfx: 'drum',
    unlock: { type: 'default' },
  },
  {
    id: 'capuchin_pickpocket',
    name: 'Capuchin Pickpocket',
    description: 'Steals wallets, kneecaps and the element of surprise. In that order.',
    classes: ['pet'],
    tier: 3,
    basePrice: 52,
    stats: { damage: 11, cooldown: 0.8, range: 7, knockback: 3, critChance: 4, critMult: 1.5, count: 1, duration: 0 },
    scaling: { meleeDamage: 0.6, luck: 0.4 },
    behavior: 'pet',
    behaviorParams: { petSpeed: 9, petHp: 30, attackType: 'melee', respawn: 5 },
    onHit: [
      { trigger: 'onKill', chance: 20, do: [{ op: 'heal', amount: 1 }] },
    ],
    visual: {
      projectile: 'none',
      muzzle: 'poof',
      model: {
        base: 'custom', scale: 0.45, primary: '#a3763f', secondary: '#e8d9b0', accent: '#2b2b2b',
        parts: [
          { shape: 'sphere', size: [0.13, 0.14, 0.12], pos: [0, 0.05, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.08, 0.08, 0.06], pos: [0, 0.03, 0.1], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'box', size: [0.08, 0.06, 0.04], pos: [0.1, -0.02, 0.02], rot: [0, 0, -0.3], color: 'accent' },
        ],
        animation: 'hop',
      },
    },
    sfx: 'chitter',
    unlock: { type: 'default' },
  },
]);
