// APETATO weapons — MELEE.
// Sticks, fists, fangs and femurs for apes who like their combat hand-delivered.
// Pure frozen data. Interpreted by src/game systems; no logic lives here.

function deepFreeze(obj) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (v && typeof v === 'object') deepFreeze(v);
  }
  return Object.freeze(obj);
}

export const MELEE_WEAPONS = deepFreeze([
  {
    id: 'gorilla_fists',
    name: 'Gorilla Fists',
    description: 'Two fists, zero patience. The original banana-opening technology.',
    classes: ['melee'],
    tier: 1,
    basePrice: 12,
    stats: { damage: 3, cooldown: 0.5, range: 1.8, knockback: 3, critChance: 3, critMult: 1.5 },
    scaling: { meleeDamage: 1.0, damagePct: 1.0 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 100, alternate: true },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'impact_dust',
      model: {
        base: 'custom', scale: 0.5, primary: '#7a5233', secondary: '#4b3220', accent: '#d9b38c',
        parts: [
          { shape: 'sphere', size: [0.3, 0.26, 0.3], pos: [0, 0, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.28, 0.12, 0.1], pos: [0, -0.12, 0.1], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'thud',
    unlock: { type: 'default' },
  },
  {
    id: 'peel_slapper',
    name: 'Peel Slapper',
    description: 'A damp banana peel on a stick. The slap echoes for generations.',
    classes: ['melee'],
    tier: 1,
    basePrice: 12,
    stats: { damage: 4, cooldown: 0.65, range: 2.0, knockback: 4, critChance: 3, critMult: 1.5 },
    scaling: { meleeDamage: 1.0 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 130 },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'slap_star',
      model: {
        base: 'custom', scale: 0.55, primary: '#ffd93b', secondary: '#8a5a2b', accent: '#6b4a1f',
        parts: [
          { shape: 'cylinder', size: [0.05, 0.5, 0.05], pos: [0, 0, 0], rot: [0, 0, 0.3], color: 'secondary' },
          { shape: 'cone', size: [0.16, 0.3, 0.16], pos: [0, 0.35, 0], rot: [0, 0, 2.6], color: 'primary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'slap',
    unlock: { type: 'default' },
  },
  {
    id: 'vine_whip',
    name: 'Vine Whip',
    description: 'Freshly yanked jungle vine. Still mad about the yanking.',
    classes: ['melee', 'speed'],
    tier: 1,
    basePrice: 14,
    stats: { damage: 2, cooldown: 0.35, range: 3.4, knockback: 2, critChance: 3, critMult: 1.5 },
    scaling: { meleeDamage: 0.8, attackSpeed: 0.3 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 70, whip: true },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'leaf_flick',
      model: {
        base: 'custom', scale: 0.55, primary: '#3f7d2c', secondary: '#2c5720', accent: '#8bc34a',
        parts: [
          { shape: 'cylinder', size: [0.04, 0.55, 0.04], pos: [0, 0, 0], rot: [0, 0, 0.5], color: 'primary' },
          { shape: 'sphere', size: [0.08, 0.08, 0.08], pos: [0, 0.3, 0], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'whip',
    unlock: { type: 'default' },
  },
  {
    id: 'bamboo_spear',
    name: 'Bamboo Spear',
    description: 'Pointy on one end, philosophical on the other. Poke responsibly.',
    classes: ['melee', 'precision'],
    tier: 1,
    basePrice: 14,
    stats: { damage: 5, cooldown: 0.85, range: 3.0, knockback: 3, critChance: 5, critMult: 1.5, pierce: 2 },
    scaling: { meleeDamage: 1.0, range: 0.3 },
    behavior: 'melee_thrust',
    behaviorParams: { lunge: 0.5 },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'poke_flash',
      model: {
        base: 'custom', scale: 0.6, primary: '#c9b458', secondary: '#7d6a2f', accent: '#e8e0b0',
        parts: [
          { shape: 'cylinder', size: [0.04, 0.7, 0.04], pos: [0, 0, 0], rot: [1.57, 0, 0], color: 'primary' },
          { shape: 'cone', size: [0.06, 0.18, 0.06], pos: [0, 0, 0.42], rot: [1.57, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'swish',
    unlock: { type: 'default' },
  },
  {
    id: 'banana_shiv',
    name: 'Banana Shiv',
    description: 'Sharpened in the shadows of the fruit bowl. Aim between the ribs.',
    classes: ['melee', 'crit'],
    tier: 1,
    basePrice: 15,
    stats: { damage: 2, cooldown: 0.35, range: 1.5, knockback: 1, critChance: 25, critMult: 2.5 },
    scaling: { meleeDamage: 0.8, critChance: 0.5 },
    behavior: 'melee_thrust',
    behaviorParams: { lunge: 0.3, backstabBonus: 0.5 },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'glint',
      model: {
        base: 'custom', scale: 0.45, primary: '#ffe24a', secondary: '#2b2b2b', accent: '#fff7c9',
        parts: [
          { shape: 'box', size: [0.05, 0.05, 0.3], pos: [0, 0, 0.15], rot: [0, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.08, 0.08, 0.1], pos: [0, 0, -0.05], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'shink',
    unlock: { type: 'default' },
  },
  {
    id: 'coconut_club',
    name: 'Coconut Club',
    description: 'A coconut lashed to a branch. Membership fees paid in concussions.',
    classes: ['melee'],
    tier: 1,
    basePrice: 13,
    stats: { damage: 7, cooldown: 1.1, range: 2.2, knockback: 8, critChance: 3, critMult: 1.5 },
    scaling: { meleeDamage: 1.1, knockback: 0.5 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 110, overhead: true },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'impact_dust',
      model: {
        base: 'custom', scale: 0.6, primary: '#6b4a2b', secondary: '#4b3220', accent: '#a3865e',
        parts: [
          { shape: 'cylinder', size: [0.05, 0.5, 0.05], pos: [0, 0, 0], rot: [0, 0, 0.4], color: 'secondary' },
          { shape: 'sphere', size: [0.22, 0.22, 0.22], pos: [0, 0.35, 0], rot: [0, 0, 0], color: 'primary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'bonk',
    unlock: { type: 'default' },
  },
  {
    id: 'branch_boppers',
    name: 'Branch Boppers',
    description: 'Twin drumming sticks. Play the bongo solo of somebody\'s doom.',
    classes: ['melee', 'speed'],
    tier: 1,
    basePrice: 14,
    stats: { damage: 2, cooldown: 0.3, range: 1.7, knockback: 2, critChance: 3, critMult: 1.5 },
    scaling: { meleeDamage: 0.7, attackSpeed: 0.4 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 80, alternate: true },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'bop_note',
      model: {
        base: 'custom', scale: 0.45, primary: '#8a5a2b', secondary: '#5d3d1e', accent: '#d9b38c',
        parts: [
          { shape: 'cylinder', size: [0.04, 0.4, 0.04], pos: [-0.08, 0, 0], rot: [0, 0, 0.2], color: 'primary' },
          { shape: 'cylinder', size: [0.04, 0.4, 0.04], pos: [0.08, 0, 0], rot: [0, 0, -0.2], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'bop',
    unlock: { type: 'default' },
  },
  {
    id: 'ape_katana',
    name: 'Ape Katana',
    description: 'Folded one thousand times, mostly out of nervous energy. Honor the peel.',
    classes: ['melee', 'crit'],
    tier: 2,
    basePrice: 30,
    stats: { damage: 6, cooldown: 0.6, range: 2.6, knockback: 3, critChance: 20, critMult: 2.2 },
    scaling: { meleeDamage: 1.0, critDamage: 0.4 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 150, slashTrail: true },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'slash_arc',
      model: {
        base: 'custom', scale: 0.65, primary: '#dfe6ec', secondary: '#2b2b2b', accent: '#ffd93b',
        parts: [
          { shape: 'box', size: [0.04, 0.04, 0.6], pos: [0, 0, 0.3], rot: [0, 0, 0], color: 'primary' },
          { shape: 'cylinder', size: [0.05, 0.16, 0.05], pos: [0, 0, -0.1], rot: [1.57, 0, 0], color: 'secondary' },
          { shape: 'torus', size: [0.08, 0.02, 0.08], pos: [0, 0, 0.0], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'slice',
    unlock: { type: 'default' },
  },
  {
    id: 'jungle_machete',
    name: 'Jungle Machete',
    description: 'Clears brush, clears schedules, clears the immediate area.',
    classes: ['melee'],
    tier: 2,
    basePrice: 26,
    stats: { damage: 7, cooldown: 0.7, range: 2.4, knockback: 4, critChance: 4, critMult: 1.5 },
    scaling: { meleeDamage: 1.0, harvesting: 0.2 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 140 },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'slash_arc',
      model: {
        base: 'custom', scale: 0.6, primary: '#b8c4cc', secondary: '#4b3220', accent: '#3f7d2c',
        parts: [
          { shape: 'box', size: [0.06, 0.03, 0.45], pos: [0, 0, 0.22], rot: [0, 0.1, 0], color: 'primary' },
          { shape: 'box', size: [0.07, 0.07, 0.14], pos: [0, 0, -0.08], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'chop',
    unlock: { type: 'default' },
  },
  {
    id: 'fossil_femur',
    name: 'Fossil Femur',
    description: 'Prehistoric leg bone. Whoever owned it no longer needs it. You do.',
    classes: ['melee', 'lifesteal'],
    tier: 2,
    basePrice: 28,
    stats: { damage: 9, cooldown: 1.0, range: 2.3, knockback: 6, critChance: 3, critMult: 1.5 },
    scaling: { meleeDamage: 1.1, lifesteal: 0.3 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 120, overhead: true },
    onHit: [
      { trigger: 'onHit', chance: 15, do: [{ op: 'heal', amount: 1 }] },
    ],
    visual: {
      projectile: 'none',
      muzzle: 'bone_dust',
      model: {
        base: 'custom', scale: 0.6, primary: '#e8e0d0', secondary: '#c9bfa8', accent: '#8a8070',
        parts: [
          { shape: 'cylinder', size: [0.06, 0.45, 0.06], pos: [0, 0, 0], rot: [0, 0, 0.3], color: 'primary' },
          { shape: 'sphere', size: [0.12, 0.1, 0.12], pos: [0, 0.28, 0], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'sphere', size: [0.12, 0.1, 0.12], pos: [0, -0.28, 0], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'bonk',
    unlock: { type: 'default' },
  },
  {
    id: 'thorn_gauntlets',
    name: 'Thorn Gauntlets',
    description: 'Bramble mittens. Every punch files a small toxicology report.',
    classes: ['melee', 'poison'],
    tier: 2,
    basePrice: 29,
    stats: { damage: 5, cooldown: 0.55, range: 1.8, knockback: 2, critChance: 3, critMult: 1.5 },
    scaling: { meleeDamage: 0.9, elementalDamage: 0.4 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 90, alternate: true },
    onHit: [
      { trigger: 'onHit', chance: 35, do: [{ op: 'status', status: 'poison', dps: 2, duration: 2, target: 'target' }] },
    ],
    visual: {
      projectile: 'none',
      muzzle: 'thorn_burst',
      model: {
        base: 'custom', scale: 0.5, primary: '#3f7d2c', secondary: '#2c5720', accent: '#a5d64a',
        parts: [
          { shape: 'sphere', size: [0.24, 0.2, 0.24], pos: [0, 0, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'cone', size: [0.05, 0.14, 0.05], pos: [0.12, 0.1, 0], rot: [0, 0, -0.6], color: 'accent' },
          { shape: 'cone', size: [0.05, 0.14, 0.05], pos: [-0.12, 0.1, 0], rot: [0, 0, 0.6], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'thud',
    unlock: { type: 'default' },
  },
  {
    id: 'silverback_smasher',
    name: 'Silverback Smasher',
    description: 'A slab of granite with grip tape. Diplomacy\'s final form.',
    classes: ['melee'],
    tier: 3,
    basePrice: 52,
    stats: { damage: 22, cooldown: 1.4, range: 2.8, knockback: 12, critChance: 3, critMult: 1.5 },
    scaling: { meleeDamage: 1.2, maxHp: 0.2 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 100, overhead: true, groundShake: true },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'rock_shards',
      model: {
        base: 'custom', scale: 0.75, primary: '#8f9aa3', secondary: '#5d666e', accent: '#4b3220',
        parts: [
          { shape: 'cylinder', size: [0.06, 0.5, 0.06], pos: [0, 0, 0], rot: [0, 0, 0.35], color: 'accent' },
          { shape: 'box', size: [0.3, 0.28, 0.24], pos: [0, 0.38, 0], rot: [0.3, 0.4, 0], color: 'primary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'crunch',
    unlock: { type: 'default' },
  },
  {
    id: 'tail_spin_staff',
    name: 'Tail Spin Staff',
    description: 'Strap a staff to your tail and become a very rude ceiling fan.',
    classes: ['melee', 'speed'],
    tier: 3,
    basePrice: 48,
    stats: { damage: 8, cooldown: 0.55, range: 2.5, knockback: 4, critChance: 4, critMult: 1.5 },
    scaling: { meleeDamage: 0.9, attackSpeed: 0.4 },
    behavior: 'melee_spin',
    behaviorParams: { revolutions: 1 },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'spin_blur',
      model: {
        base: 'custom', scale: 0.65, primary: '#c9b458', secondary: '#8a5a2b', accent: '#ffd93b',
        parts: [
          { shape: 'cylinder', size: [0.04, 0.8, 0.04], pos: [0, 0, 0], rot: [0, 0, 1.57], color: 'primary' },
          { shape: 'sphere', size: [0.08, 0.08, 0.08], pos: [0.42, 0, 0], rot: [0, 0, 0], color: 'accent' },
          { shape: 'sphere', size: [0.08, 0.08, 0.08], pos: [-0.42, 0, 0], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'spin',
      },
    },
    sfx: 'whoosh',
    unlock: { type: 'default' },
  },
  {
    id: 'leech_vine_lash',
    name: 'Leech Vine Lash',
    description: 'A vine with an appetite. It drinks first, you get the refill.',
    classes: ['melee', 'lifesteal'],
    tier: 3,
    basePrice: 55,
    stats: { damage: 12, cooldown: 0.8, range: 3.2, knockback: 3, critChance: 3, critMult: 1.5 },
    scaling: { meleeDamage: 1.0, lifesteal: 0.5 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 80, whip: true },
    onHit: [
      { trigger: 'onHit', chance: 25, do: [{ op: 'heal', amount: 1 }] },
    ],
    visual: {
      projectile: 'none',
      muzzle: 'red_drip',
      model: {
        base: 'custom', scale: 0.6, primary: '#7d2c3f', secondary: '#3f7d2c', accent: '#d64a5a',
        parts: [
          { shape: 'cylinder', size: [0.04, 0.6, 0.04], pos: [0, 0, 0], rot: [0, 0, 0.5], color: 'secondary' },
          { shape: 'sphere', size: [0.1, 0.1, 0.1], pos: [0, 0.32, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'cone', size: [0.04, 0.1, 0.04], pos: [0, 0.42, 0], rot: [3.14, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'slurp',
    unlock: { type: 'default' },
  },
  {
    id: 'obsidian_fang',
    name: 'Obsidian Fang',
    description: 'Volcanic glass dagger. So sharp it cuts the concept of durability.',
    classes: ['melee', 'crit'],
    tier: 4,
    basePrice: 105,
    stats: { damage: 13, cooldown: 0.5, range: 2.0, knockback: 2, critChance: 30, critMult: 3.0 },
    scaling: { meleeDamage: 1.0, critDamage: 0.6 },
    behavior: 'melee_thrust',
    behaviorParams: { lunge: 0.6, backstabBonus: 1.0 },
    onHit: [
      { trigger: 'onCrit', chance: 30, do: [{ op: 'status', status: 'bleed', dps: 4, duration: 2, target: 'target' }] },
    ],
    visual: {
      projectile: 'none',
      muzzle: 'dark_glint',
      model: {
        base: 'custom', scale: 0.55, primary: '#1c1c24', secondary: '#3a3a4a', accent: '#b04aff',
        parts: [
          { shape: 'cone', size: [0.07, 0.45, 0.07], pos: [0, 0, 0.2], rot: [1.57, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.09, 0.09, 0.1], pos: [0, 0, -0.08], rot: [0, 0, 0.785], color: 'secondary' },
          { shape: 'sphere', size: [0.05, 0.05, 0.05], pos: [0, 0, -0.14], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'shink',
    unlock: { type: 'buy', cost: 140 },
  },
  {
    id: 'kongs_girder',
    name: 'Kong\'s Girder',
    description: 'A steel I-beam borrowed from a skyscraper. The skyscraper knows better than to ask.',
    classes: ['melee'],
    tier: 4,
    basePrice: 95,
    stats: { damage: 35, cooldown: 1.5, range: 3.0, knockback: 15, critChance: 3, critMult: 1.5 },
    scaling: { meleeDamage: 1.3, knockback: 0.6 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 160, overhead: true, groundShake: true },
    onHit: [
      { trigger: 'onHit', chance: 15, do: [{ op: 'status', status: 'stun', dps: 0, duration: 0.7, target: 'target' }] },
    ],
    visual: {
      projectile: 'none',
      muzzle: 'rock_shards',
      model: {
        base: 'custom', scale: 0.85, primary: '#a33a2b', secondary: '#6e2a20', accent: '#ffd93b',
        parts: [
          { shape: 'box', size: [0.12, 0.12, 0.9], pos: [0, 0, 0.3], rot: [0, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.2, 0.04, 0.9], pos: [0, 0.08, 0.3], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'box', size: [0.2, 0.04, 0.9], pos: [0, -0.08, 0.3], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'crunch',
    unlock: { type: 'wins', count: 3 },
  },
  {
    id: 'mosquito_lance',
    name: 'Mosquito Lance',
    description: 'A proboscis on a stick. Every poke is a tiny blood donation. Yours to keep.',
    classes: ['melee', 'lifesteal'],
    tier: 1,
    basePrice: 14,
    stats: { damage: 5, cooldown: 0.8, range: 2.2, knockback: 2, critChance: 4, critMult: 1.5 },
    scaling: { meleeDamage: 0.9, lifesteal: 0.3 },
    behavior: 'melee_thrust',
    behaviorParams: { lunge: 0.4 },
    onHit: [
      { trigger: 'onHit', chance: 20, do: [{ op: 'heal', amount: 1 }] },
    ],
    visual: {
      projectile: 'none',
      muzzle: 'red_drip',
      model: {
        base: 'custom', scale: 0.55, primary: '#5d666e', secondary: '#7d2c3f', accent: '#d64a5a',
        parts: [
          { shape: 'cylinder', size: [0.03, 0.5, 0.03], pos: [0, 0, 0.1], rot: [1.57, 0, 0], color: 'primary' },
          { shape: 'cone', size: [0.04, 0.16, 0.04], pos: [0, 0, 0.4], rot: [1.57, 0, 0], color: 'accent' },
          { shape: 'sphere', size: [0.07, 0.07, 0.07], pos: [0, 0, -0.16], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'shink',
    unlock: { type: 'default' },
  },
]);
