// APETATO weapons — RANGED.
// Things that fling other things. Peels, pebbles, darts and regret.
// Pure frozen data. Interpreted by src/game systems; no logic lives here.

function deepFreeze(obj) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (v && typeof v === 'object') deepFreeze(v);
  }
  return Object.freeze(obj);
}

export const RANGED_WEAPONS = deepFreeze([
  {
    id: 'banana_pistol',
    name: 'Banana Pistol',
    description: 'Point the curvy end at trouble. Reloads by ripening.',
    classes: ['ranged'],
    tier: 1,
    basePrice: 12,
    stats: { damage: 3, cooldown: 0.5, range: 9, knockback: 1, critChance: 4, critMult: 1.5, projectileSpeed: 14 },
    scaling: { rangedDamage: 1.0, damagePct: 1.0 },
    behavior: 'projectile',
    behaviorParams: {},
    onHit: [],
    visual: {
      projectile: 'peel_round',
      muzzle: 'yellow_flash',
      model: {
        base: 'custom', scale: 0.5, primary: '#ffd93b', secondary: '#8a5a2b', accent: '#2b2b2b',
        parts: [
          { shape: 'box', size: [0.08, 0.1, 0.3], pos: [0, 0, 0.1], rot: [0.2, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.07, 0.16, 0.08], pos: [0, -0.1, -0.05], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'pop',
    unlock: { type: 'default' },
  },
  {
    id: 'monkey_slingshot',
    name: 'Monkey Slingshot',
    description: 'Forked stick plus rubber plus rock. Ancient artillery, timeless attitude.',
    classes: ['ranged'],
    tier: 1,
    basePrice: 13,
    stats: { damage: 5, cooldown: 0.8, range: 8, knockback: 3, critChance: 4, critMult: 1.5, projectileSpeed: 12 },
    scaling: { rangedDamage: 1.0, knockback: 0.3 },
    behavior: 'projectile',
    behaviorParams: {},
    onHit: [],
    visual: {
      projectile: 'pebble',
      muzzle: 'twang',
      model: {
        base: 'custom', scale: 0.5, primary: '#8a5a2b', secondary: '#d9534f', accent: '#5d3d1e',
        parts: [
          { shape: 'cylinder', size: [0.04, 0.3, 0.04], pos: [0, -0.1, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'cylinder', size: [0.03, 0.2, 0.03], pos: [-0.07, 0.12, 0], rot: [0, 0, 0.5], color: 'accent' },
          { shape: 'cylinder', size: [0.03, 0.2, 0.03], pos: [0.07, 0.12, 0], rot: [0, 0, -0.5], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'twang',
    unlock: { type: 'default' },
  },
  {
    id: 'pebble_pelter',
    name: 'Pebble Pelter',
    description: 'A tin can of gravel and a wrist that never sleeps. Rat-a-tat-rock.',
    classes: ['ranged', 'speed'],
    tier: 1,
    basePrice: 13,
    stats: { damage: 1, cooldown: 0.18, range: 6.5, knockback: 1, critChance: 3, critMult: 1.5, projectileSpeed: 13, spread: 6 },
    scaling: { rangedDamage: 0.6, attackSpeed: 0.4 },
    behavior: 'projectile',
    behaviorParams: {},
    onHit: [],
    visual: {
      projectile: 'pebble',
      muzzle: 'dust_puff',
      model: {
        base: 'custom', scale: 0.45, primary: '#8f9aa3', secondary: '#5d666e', accent: '#c9b458',
        parts: [
          { shape: 'cylinder', size: [0.1, 0.16, 0.1], pos: [0, 0, 0], rot: [0.3, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.06, 0.06, 0.06], pos: [0, 0.1, 0.05], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'tick',
    unlock: { type: 'default' },
  },
  {
    id: 'poison_dart_blowgun',
    name: 'Poison Dart Blowgun',
    description: 'Deep breath in, bad afternoon out. Darts marinated in frog regrets.',
    classes: ['ranged', 'poison'],
    tier: 1,
    basePrice: 15,
    stats: { damage: 2, cooldown: 0.45, range: 8.5, knockback: 0, critChance: 3, critMult: 1.5, projectileSpeed: 16 },
    scaling: { rangedDamage: 0.7, elementalDamage: 0.5 },
    behavior: 'projectile',
    behaviorParams: {},
    onHit: [
      { trigger: 'onHit', chance: 50, do: [{ op: 'status', status: 'poison', dps: 2, duration: 2, target: 'target' }] },
    ],
    visual: {
      projectile: 'dart',
      muzzle: 'breath_puff',
      model: {
        base: 'custom', scale: 0.55, primary: '#c9b458', secondary: '#3f7d2c', accent: '#a5d64a',
        parts: [
          { shape: 'cylinder', size: [0.04, 0.6, 0.04], pos: [0, 0, 0.1], rot: [1.57, 0, 0], color: 'primary' },
          { shape: 'torus', size: [0.06, 0.015, 0.06], pos: [0, 0, -0.18], rot: [1.57, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'pfft',
    unlock: { type: 'default' },
  },
  {
    id: 'peel_flinger',
    name: 'Peel Flinger',
    description: 'A spring-loaded fruit bowl. Serves a balanced breakfast of ouch.',
    classes: ['ranged'],
    tier: 1,
    basePrice: 14,
    stats: { damage: 2, cooldown: 0.9, range: 6, knockback: 2, critChance: 3, critMult: 1.5, projectileSpeed: 11, count: 3, spread: 30 },
    scaling: { rangedDamage: 0.8 },
    behavior: 'shotgun',
    behaviorParams: {},
    onHit: [],
    visual: {
      projectile: 'peel_round',
      muzzle: 'yellow_flash',
      model: {
        base: 'custom', scale: 0.5, primary: '#ffd93b', secondary: '#6b4a1f', accent: '#8a5a2b',
        parts: [
          { shape: 'sphere', size: [0.18, 0.1, 0.18], pos: [0, 0, 0], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'cone', size: [0.08, 0.14, 0.08], pos: [0, 0.08, 0.06], rot: [0.6, 0, 0], color: 'primary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'sproing',
    unlock: { type: 'default' },
  },
  {
    id: 'twig_bow',
    name: 'Twig Bow',
    description: 'Bent branch, borrowed shoelace. Robin Hood but make it primate.',
    classes: ['ranged', 'precision'],
    tier: 1,
    basePrice: 15,
    stats: { damage: 6, cooldown: 1.0, range: 12, knockback: 2, critChance: 5, critMult: 1.5, projectileSpeed: 18, pierce: 1 },
    scaling: { rangedDamage: 1.0, range: 0.3 },
    behavior: 'projectile',
    behaviorParams: { chargeUp: 0.2 },
    onHit: [],
    visual: {
      projectile: 'arrow',
      muzzle: 'twang',
      model: {
        base: 'custom', scale: 0.6, primary: '#8a5a2b', secondary: '#e8e0b0', accent: '#3f7d2c',
        parts: [
          { shape: 'torus', size: [0.24, 0.02, 0.24], pos: [0, 0, 0], rot: [0, 1.57, 0], color: 'primary' },
          { shape: 'cylinder', size: [0.02, 0.5, 0.02], pos: [0, 0, 0.05], rot: [1.57, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'twang',
    unlock: { type: 'default' },
  },
  {
    id: 'seed_spitter',
    name: 'Seed Spitter',
    description: 'Watermelon seeds at mach chew. Spitting is finally a career.',
    classes: ['ranged'],
    tier: 1,
    basePrice: 13,
    stats: { damage: 2, cooldown: 1.0, range: 8, knockback: 1, critChance: 3, critMult: 1.5, projectileSpeed: 15, count: 3 },
    scaling: { rangedDamage: 0.8, attackSpeed: 0.2 },
    behavior: 'burst',
    behaviorParams: { burstInterval: 0.08 },
    onHit: [],
    visual: {
      projectile: 'seed',
      muzzle: 'spit_puff',
      model: {
        base: 'custom', scale: 0.45, primary: '#3f7d2c', secondary: '#d9534f', accent: '#2b2b2b',
        parts: [
          { shape: 'sphere', size: [0.16, 0.14, 0.2], pos: [0, 0, 0], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'sphere', size: [0.05, 0.05, 0.05], pos: [0, 0.02, 0.14], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'ptoo',
    unlock: { type: 'default' },
  },
  {
    id: 'coconut_crossbow',
    name: 'Coconut Crossbow',
    description: 'Fires whole coconuts through several unfortunate torsos.',
    classes: ['ranged', 'precision'],
    tier: 2,
    basePrice: 30,
    stats: { damage: 11, cooldown: 1.2, range: 12, knockback: 5, critChance: 5, critMult: 1.5, projectileSpeed: 16, pierce: 2 },
    scaling: { rangedDamage: 1.1, projectileSpeed: 0.3 },
    behavior: 'projectile',
    behaviorParams: {},
    onHit: [],
    visual: {
      projectile: 'coconut',
      muzzle: 'twang',
      model: {
        base: 'custom', scale: 0.6, primary: '#5d3d1e', secondary: '#8a5a2b', accent: '#b8c4cc',
        parts: [
          { shape: 'box', size: [0.06, 0.05, 0.5], pos: [0, 0, 0.1], rot: [0, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.4, 0.04, 0.05], pos: [0, 0, 0.28], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'sphere', size: [0.1, 0.1, 0.1], pos: [0, 0.05, 0], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'thunk',
    unlock: { type: 'default' },
  },
  {
    id: 'banana_burst_rifle',
    name: 'Banana Burst Rifle',
    description: 'Three peels per trigger pull. Tactical potassium delivery.',
    classes: ['ranged'],
    tier: 2,
    basePrice: 28,
    stats: { damage: 3, cooldown: 0.9, range: 10, knockback: 1, critChance: 4, critMult: 1.5, projectileSpeed: 17, count: 3 },
    scaling: { rangedDamage: 1.0 },
    behavior: 'burst',
    behaviorParams: { burstInterval: 0.07 },
    onHit: [],
    visual: {
      projectile: 'peel_round',
      muzzle: 'yellow_flash',
      model: {
        base: 'custom', scale: 0.6, primary: '#ffd93b', secondary: '#2b2b2b', accent: '#8a5a2b',
        parts: [
          { shape: 'box', size: [0.07, 0.08, 0.55], pos: [0, 0, 0.15], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'box', size: [0.06, 0.12, 0.1], pos: [0, -0.08, -0.05], rot: [0, 0, 0], color: 'accent' },
          { shape: 'box', size: [0.05, 0.05, 0.2], pos: [0, 0.07, 0.2], rot: [0, 0, 0], color: 'primary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'burst_pop',
    unlock: { type: 'default' },
  },
  {
    id: 'jungle_chatter_gun',
    name: 'Jungle Chatter Gun',
    description: 'A machine gun that never stops talking. Neither do the neighbors, now.',
    classes: ['ranged', 'speed'],
    tier: 2,
    basePrice: 32,
    stats: { damage: 2, cooldown: 0.2, range: 9, knockback: 1, critChance: 3, critMult: 1.5, projectileSpeed: 15, spread: 8 },
    scaling: { rangedDamage: 0.8, attackSpeed: 0.4 },
    behavior: 'projectile',
    behaviorParams: { spinUp: true },
    onHit: [],
    visual: {
      projectile: 'seed',
      muzzle: 'rapid_flash',
      model: {
        base: 'custom', scale: 0.65, primary: '#3f7d2c', secondary: '#2b2b2b', accent: '#c9b458',
        parts: [
          { shape: 'cylinder', size: [0.06, 0.5, 0.06], pos: [0, 0, 0.15], rot: [1.57, 0, 0], color: 'secondary' },
          { shape: 'box', size: [0.12, 0.14, 0.25], pos: [0, -0.02, -0.1], rot: [0, 0, 0], color: 'primary' },
          { shape: 'cylinder', size: [0.08, 0.12, 0.08], pos: [0, -0.12, 0], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'chatter',
    unlock: { type: 'default' },
  },
  {
    id: 'peel_scattergun',
    name: 'Peel Scattergun',
    description: 'A trombone of violence. One honk, wall-to-wall banana.',
    classes: ['ranged'],
    tier: 2,
    basePrice: 27,
    stats: { damage: 2.5, cooldown: 1.1, range: 6.5, knockback: 6, critChance: 3, critMult: 1.5, projectileSpeed: 12, count: 4, spread: 40 },
    scaling: { rangedDamage: 0.9, knockback: 0.4 },
    behavior: 'shotgun',
    behaviorParams: {},
    onHit: [],
    visual: {
      projectile: 'peel_round',
      muzzle: 'wide_flash',
      model: {
        base: 'custom', scale: 0.6, primary: '#b8860b', secondary: '#5d3d1e', accent: '#ffd93b',
        parts: [
          { shape: 'cone', size: [0.14, 0.4, 0.14], pos: [0, 0, 0.25], rot: [-1.57, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.07, 0.1, 0.25], pos: [0, -0.04, -0.1], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'boom_pop',
    unlock: { type: 'default' },
  },
  {
    id: 'longeye_sniper_reed',
    name: 'Longeye Sniper Reed',
    description: 'A two-meter reed with a dewdrop scope. Sees your future. Ends it.',
    classes: ['ranged', 'crit'],
    tier: 3,
    basePrice: 55,
    stats: { damage: 20, cooldown: 1.5, range: 14, knockback: 4, critChance: 25, critMult: 2.5, projectileSpeed: 26, pierce: 3 },
    scaling: { rangedDamage: 1.2, critDamage: 0.5 },
    behavior: 'projectile',
    behaviorParams: { chargeUp: 0.3, tracer: true },
    onHit: [],
    visual: {
      projectile: 'long_dart',
      muzzle: 'crack_flash',
      model: {
        base: 'custom', scale: 0.7, primary: '#c9b458', secondary: '#2b2b2b', accent: '#7ec8e3',
        parts: [
          { shape: 'cylinder', size: [0.04, 0.9, 0.04], pos: [0, 0, 0.2], rot: [1.57, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.07, 0.07, 0.07], pos: [0, 0.08, -0.05], rot: [0, 0, 0], color: 'accent' },
          { shape: 'box', size: [0.05, 0.1, 0.12], pos: [0, -0.07, -0.15], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'crack',
    unlock: { type: 'default' },
  },
  {
    id: 'viper_dart_rifle',
    name: 'Viper Dart Rifle',
    description: 'Bolt-action blowgun chambered in .32 caliber snake opinion.',
    classes: ['ranged', 'poison'],
    tier: 3,
    basePrice: 50,
    stats: { damage: 9, cooldown: 0.7, range: 11, knockback: 1, critChance: 4, critMult: 1.5, projectileSpeed: 20 },
    scaling: { rangedDamage: 0.9, elementalDamage: 0.6 },
    behavior: 'projectile',
    behaviorParams: {},
    onHit: [
      { trigger: 'onHit', chance: 35, do: [{ op: 'status', status: 'poison', dps: 4, duration: 3, target: 'target' }] },
    ],
    visual: {
      projectile: 'dart',
      muzzle: 'green_hiss',
      model: {
        base: 'custom', scale: 0.65, primary: '#3f7d2c', secondary: '#2c5720', accent: '#a5d64a',
        parts: [
          { shape: 'cylinder', size: [0.05, 0.7, 0.05], pos: [0, 0, 0.15], rot: [1.57, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.06, 0.1, 0.2], pos: [0, -0.06, -0.15], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'cone', size: [0.04, 0.1, 0.04], pos: [0, 0.06, 0.35], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'hiss_pop',
    unlock: { type: 'default' },
  },
  {
    id: 'double_peel_blunderbuss',
    name: 'Double Peel Blunderbuss',
    description: 'Both barrels loaded with breakfast. Say hello to the fruit wall.',
    classes: ['ranged'],
    tier: 3,
    basePrice: 52,
    stats: { damage: 3.2, cooldown: 1.1, range: 6, knockback: 8, critChance: 3, critMult: 1.5, projectileSpeed: 12, count: 5, spread: 45 },
    scaling: { rangedDamage: 1.0, knockback: 0.5 },
    behavior: 'shotgun',
    behaviorParams: { recoilDash: 0.6 },
    onHit: [],
    visual: {
      projectile: 'peel_round',
      muzzle: 'wide_flash',
      model: {
        base: 'custom', scale: 0.65, primary: '#b8860b', secondary: '#5d3d1e', accent: '#ffd93b',
        parts: [
          { shape: 'cone', size: [0.12, 0.35, 0.12], pos: [-0.07, 0, 0.22], rot: [-1.57, 0, 0], color: 'primary' },
          { shape: 'cone', size: [0.12, 0.35, 0.12], pos: [0.07, 0, 0.22], rot: [-1.57, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.16, 0.1, 0.25], pos: [0, -0.04, -0.1], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'double_boom',
    unlock: { type: 'default' },
  },
  {
    id: 'golden_banana_magnum',
    name: 'Golden Banana Magnum',
    description: 'The most powerful handfruit in the world. Feel lucky, chimp?',
    classes: ['ranged', 'crit'],
    tier: 4,
    basePrice: 100,
    stats: { damage: 24, cooldown: 1.0, range: 11, knockback: 7, critChance: 30, critMult: 3.0, projectileSpeed: 22, pierce: 2 },
    scaling: { rangedDamage: 1.1, critDamage: 0.6, luck: 0.2 },
    behavior: 'projectile',
    behaviorParams: { tracer: true },
    onHit: [
      { trigger: 'onCrit', chance: 100, do: [{ op: 'coins', amount: 1 }] },
    ],
    visual: {
      projectile: 'gold_round',
      muzzle: 'gold_flash',
      model: {
        base: 'custom', scale: 0.6, primary: '#ffcf40', secondary: '#8a5a2b', accent: '#fff2b0',
        parts: [
          { shape: 'box', size: [0.09, 0.11, 0.4], pos: [0, 0, 0.12], rot: [0.15, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.08, 0.16, 0.09], pos: [0, -0.11, -0.06], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'torus', size: [0.06, 0.015, 0.06], pos: [0, 0.08, 0.05], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'magnum_bang',
    unlock: { type: 'buy', cost: 130 },
  },
  {
    id: 'hurricane_peel_cannon',
    name: 'Hurricane Peel Cannon',
    description: 'Category five fruit weather. Forecast: hazardous flooring everywhere.',
    classes: ['ranged', 'speed'],
    tier: 4,
    basePrice: 95,
    stats: { damage: 4, cooldown: 0.16, range: 9, knockback: 2, critChance: 3, critMult: 1.5, projectileSpeed: 18, spread: 12 },
    scaling: { rangedDamage: 0.9, attackSpeed: 0.5 },
    behavior: 'projectile',
    behaviorParams: { spinUp: true, heatWobble: true },
    onHit: [],
    visual: {
      projectile: 'peel_round',
      muzzle: 'rapid_flash',
      model: {
        base: 'custom', scale: 0.75, primary: '#ffd93b', secondary: '#2b2b2b', accent: '#d9534f',
        parts: [
          { shape: 'cylinder', size: [0.07, 0.45, 0.07], pos: [-0.06, 0, 0.2], rot: [1.57, 0, 0], color: 'secondary' },
          { shape: 'cylinder', size: [0.07, 0.45, 0.07], pos: [0.06, 0, 0.2], rot: [1.57, 0, 0], color: 'secondary' },
          { shape: 'box', size: [0.18, 0.16, 0.3], pos: [0, 0, -0.12], rot: [0, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.06, 0.06, 0.06], pos: [0, 0.1, -0.12], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'roar',
    unlock: { type: 'wins', count: 2 },
  },
]);
