// APETATO weapons — TECH.
// Engineering-grade nonsense: turrets, lasers, saws and one railgun that
// should absolutely not exist. Pure frozen data; systems interpret.

function deepFreeze(obj) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (v && typeof v === 'object') deepFreeze(v);
  }
  return Object.freeze(obj);
}

export const TECH_WEAPONS = deepFreeze([
  {
    id: 'gear_flick_gauntlet',
    name: 'Gear Flick Gauntlet',
    description: 'A wrist-mounted gear dispenser. OSHA has stopped returning our calls.',
    classes: ['tech'],
    tier: 1,
    basePrice: 13,
    stats: { damage: 4, cooldown: 0.7, range: 8, knockback: 2, critChance: 3, critMult: 1.5, projectileSpeed: 13 },
    scaling: { engineering: 1.0, damagePct: 1.0 },
    behavior: 'projectile',
    behaviorParams: { spinVisual: true },
    onHit: [],
    visual: {
      projectile: 'gear',
      muzzle: 'spark_puff',
      model: {
        base: 'custom', scale: 0.5, primary: '#8f9aa3', secondary: '#c9b458', accent: '#5d666e',
        parts: [
          { shape: 'box', size: [0.16, 0.1, 0.2], pos: [0, 0, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'torus', size: [0.08, 0.02, 0.08], pos: [0, 0.07, 0.08], rot: [1.57, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'clink',
    unlock: { type: 'default' },
  },
  {
    id: 'wrench_of_wrath',
    name: 'Wrench of Wrath',
    description: 'Tightens bolts, loosens teeth. Certified for both jobs.',
    classes: ['tech', 'melee'],
    tier: 1,
    basePrice: 14,
    stats: { damage: 5, cooldown: 0.8, range: 2.0, knockback: 5, critChance: 4, critMult: 1.5 },
    scaling: { meleeDamage: 0.8, engineering: 0.6 },
    behavior: 'melee_swing',
    behaviorParams: { arc: 110 },
    onHit: [],
    visual: {
      projectile: 'none',
      muzzle: 'spark_puff',
      model: {
        base: 'custom', scale: 0.55, primary: '#8f9aa3', secondary: '#d9302b', accent: '#5d666e',
        parts: [
          { shape: 'cylinder', size: [0.04, 0.4, 0.04], pos: [0, 0, 0], rot: [0, 0, 0.3], color: 'primary' },
          { shape: 'torus', size: [0.09, 0.03, 0.09], pos: [0, 0.26, 0], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'clang',
    unlock: { type: 'default' },
  },
  {
    id: 'scrap_turret_kit',
    name: 'Scrap Turret Kit',
    description: 'Some assembly required. The manual is a single angry diagram.',
    classes: ['tech', 'turret'],
    tier: 1,
    basePrice: 16,
    stats: { damage: 3, cooldown: 0.8, range: 8, knockback: 1, critChance: 3, critMult: 1.5, projectileSpeed: 12, duration: 10 },
    scaling: { engineering: 1.2 },
    behavior: 'turret',
    behaviorParams: { deployCooldown: 6, maxActive: 2, turretFireRate: 0.8 },
    onHit: [],
    visual: {
      projectile: 'pebble',
      muzzle: 'spark_puff',
      model: {
        base: 'custom', scale: 0.5, primary: '#8a5a2b', secondary: '#8f9aa3', accent: '#d9302b',
        parts: [
          { shape: 'box', size: [0.2, 0.08, 0.2], pos: [0, -0.06, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'cylinder', size: [0.04, 0.2, 0.04], pos: [0, 0.06, 0.08], rot: [1.57, 0, 0], color: 'secondary' },
          { shape: 'sphere', size: [0.04, 0.04, 0.04], pos: [0, 0.12, 0], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'ratchet',
    unlock: { type: 'default' },
  },
  {
    id: 'laser_banana',
    name: 'Laser Banana',
    description: 'Peer-reviewed proof that fruit can be weaponized coherent light.',
    classes: ['tech'],
    tier: 2,
    basePrice: 31,
    stats: { damage: 4, cooldown: 0.4, range: 10, knockback: 0, critChance: 4, critMult: 1.5, pierce: 3, duration: 0.3 },
    scaling: { engineering: 0.8, elementalDamage: 0.5 },
    behavior: 'beam',
    behaviorParams: { width: 0.25 },
    onHit: [],
    visual: {
      projectile: 'laser_line',
      muzzle: 'red_glow',
      model: {
        base: 'custom', scale: 0.55, primary: '#ffd93b', secondary: '#d9302b', accent: '#2b2b2b',
        parts: [
          { shape: 'box', size: [0.08, 0.1, 0.35], pos: [0, 0, 0.08], rot: [0.15, 0, 0], color: 'primary' },
          { shape: 'cylinder', size: [0.03, 0.1, 0.03], pos: [0, 0.02, 0.3], rot: [1.57, 0, 0], color: 'secondary' },
          { shape: 'box', size: [0.06, 0.06, 0.08], pos: [0, -0.08, -0.08], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'pew',
    unlock: { type: 'default' },
  },
  {
    id: 'robo_banana_saw',
    name: 'Robo Banana Saw',
    description: 'A chrome banana with teeth. It circles you like a very loyal lawsuit.',
    classes: ['tech', 'melee'],
    tier: 2,
    basePrice: 30,
    stats: { damage: 6, cooldown: 0.5, range: 2.5, knockback: 3, critChance: 3, critMult: 1.5, count: 2, radius: 2.5 },
    scaling: { engineering: 0.8, meleeDamage: 0.5 },
    behavior: 'orbit',
    behaviorParams: { orbitSpeed: 4, grind: true },
    onHit: [
      { trigger: 'onHit', chance: 20, do: [{ op: 'status', status: 'bleed', dps: 2, duration: 2, target: 'target' }] },
    ],
    visual: {
      projectile: 'saw_blade',
      muzzle: 'spark_puff',
      model: {
        base: 'custom', scale: 0.5, primary: '#b8c4cc', secondary: '#ffd93b', accent: '#2b2b2b',
        parts: [
          { shape: 'torus', size: [0.16, 0.03, 0.16], pos: [0, 0, 0], rot: [1.57, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.07, 0.07, 0.07], pos: [0, 0, 0], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'cone', size: [0.03, 0.08, 0.03], pos: [0.17, 0, 0], rot: [0, 0, -1.57], color: 'accent' },
        ],
        animation: 'spin',
      },
    },
    sfx: 'buzz',
    unlock: { type: 'default' },
  },
  {
    id: 'peel_o_matic_turret',
    name: 'Peel-O-Matic Turret',
    description: 'Vending machine gone rogue. Dispenses peels at 600 rounds per banana.',
    classes: ['tech', 'turret'],
    tier: 2,
    basePrice: 34,
    stats: { damage: 4, cooldown: 0.5, range: 9, knockback: 1, critChance: 3, critMult: 1.5, projectileSpeed: 14, duration: 12 },
    scaling: { engineering: 1.3 },
    behavior: 'turret',
    behaviorParams: { deployCooldown: 7, maxActive: 2, turretFireRate: 0.5 },
    onHit: [],
    visual: {
      projectile: 'peel_round',
      muzzle: 'yellow_flash',
      model: {
        base: 'custom', scale: 0.55, primary: '#ffd93b', secondary: '#8f9aa3', accent: '#d9302b',
        parts: [
          { shape: 'box', size: [0.18, 0.22, 0.16], pos: [0, 0, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'cylinder', size: [0.04, 0.18, 0.04], pos: [0, 0.1, 0.12], rot: [1.57, 0, 0], color: 'secondary' },
          { shape: 'sphere', size: [0.04, 0.04, 0.04], pos: [0, 0.15, 0], rot: [0, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'ratchet',
    unlock: { type: 'default' },
  },
  {
    id: 'tesla_totem_turret',
    name: 'Tesla Totem Turret',
    description: 'A carved idol with a lightning grudge. Worship optional, grounding mandatory.',
    classes: ['tech', 'turret'],
    tier: 3,
    basePrice: 56,
    stats: { damage: 9, cooldown: 0.9, range: 8, knockback: 1, critChance: 3, critMult: 1.5, count: 2, duration: 12 },
    scaling: { engineering: 1.4, elementalDamage: 0.4 },
    behavior: 'turret',
    behaviorParams: { deployCooldown: 8, maxActive: 2, turretFireRate: 0.9, chainJumps: 2, chainRange: 3.5 },
    onHit: [
      { trigger: 'onHit', chance: 30, do: [{ op: 'status', status: 'shock', dps: 4, duration: 1, target: 'target' }] },
    ],
    visual: {
      projectile: 'lightning_arc',
      muzzle: 'spark_crackle',
      model: {
        base: 'custom', scale: 0.6, primary: '#8a5a2b', secondary: '#7ec8e3', accent: '#fff2b0',
        parts: [
          { shape: 'box', size: [0.16, 0.3, 0.14], pos: [0, 0, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'sphere', size: [0.09, 0.09, 0.09], pos: [0, 0.22, 0], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'cone', size: [0.04, 0.1, 0.04], pos: [0.1, 0.28, 0], rot: [0, 0, -0.5], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'zap',
    unlock: { type: 'default' },
  },
  {
    id: 'melon_mortar_turret',
    name: 'Melon Mortar Turret',
    description: 'Automated melon artillery. Rains seeds, pulp and consequences.',
    classes: ['turret', 'explosive'],
    tier: 3,
    basePrice: 54,
    stats: { damage: 16, cooldown: 1.5, range: 10, knockback: 6, critChance: 3, critMult: 1.5, radius: 2.2, duration: 12 },
    scaling: { engineering: 1.3, explosionSize: 0.5 },
    behavior: 'turret',
    behaviorParams: { deployCooldown: 9, maxActive: 1, turretFireRate: 1.5, lobbed: true },
    onHit: [],
    visual: {
      projectile: 'melon_shell',
      muzzle: 'smoke_ring',
      model: {
        base: 'custom', scale: 0.6, primary: '#3f7d2c', secondary: '#8f9aa3', accent: '#d9534f',
        parts: [
          { shape: 'box', size: [0.22, 0.1, 0.22], pos: [0, -0.08, 0], rot: [0, 0, 0], color: 'secondary' },
          { shape: 'sphere', size: [0.14, 0.14, 0.14], pos: [0, 0.05, 0], rot: [0, 0, 0], color: 'primary' },
          { shape: 'cylinder', size: [0.05, 0.2, 0.05], pos: [0, 0.16, 0.05], rot: [0.9, 0, 0], color: 'accent' },
        ],
        animation: 'none',
      },
    },
    sfx: 'mortar_thump',
    unlock: { type: 'default' },
  },
  {
    id: 'rivet_burst_pistol',
    name: 'Rivet Burst Pistol',
    description: 'Construction tool, deconstruction hobby. Three rivets per opinion.',
    classes: ['tech'],
    tier: 2,
    basePrice: 27,
    stats: { damage: 3.5, cooldown: 1.0, range: 8.5, knockback: 2, critChance: 3, critMult: 1.5, projectileSpeed: 16, count: 3 },
    scaling: { engineering: 0.9, rangedDamage: 0.4 },
    behavior: 'burst',
    behaviorParams: { burstInterval: 0.08 },
    onHit: [],
    visual: {
      projectile: 'rivet',
      muzzle: 'spark_puff',
      model: {
        base: 'custom', scale: 0.5, primary: '#d9822b', secondary: '#5d666e', accent: '#ffd93b',
        parts: [
          { shape: 'box', size: [0.08, 0.1, 0.28], pos: [0, 0, 0.08], rot: [0, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.07, 0.14, 0.08], pos: [0, -0.1, -0.05], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'clink',
    unlock: { type: 'default' },
  },
  {
    id: 'banana_railgun',
    name: 'Banana Railgun',
    description: 'Accelerates one banana to Mach Yes. The peel arrives last week.',
    classes: ['tech', 'precision'],
    tier: 4,
    basePrice: 110,
    stats: { damage: 40, cooldown: 1.8, range: 14, knockback: 10, critChance: 5, critMult: 1.5, projectileSpeed: 40, pierce: 5 },
    scaling: { engineering: 1.0, rangedDamage: 0.8, range: 0.4 },
    behavior: 'rail',
    behaviorParams: { chargeUp: 0.5, tracer: true, screenShake: true },
    onHit: [],
    visual: {
      projectile: 'rail_beam',
      muzzle: 'blue_flash',
      model: {
        base: 'custom', scale: 0.75, primary: '#2b2b2b', secondary: '#7ec8e3', accent: '#ffd93b',
        parts: [
          { shape: 'box', size: [0.08, 0.05, 0.8], pos: [0, 0.05, 0.2], rot: [0, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.08, 0.05, 0.8], pos: [0, -0.05, 0.2], rot: [0, 0, 0], color: 'primary' },
          { shape: 'box', size: [0.07, 0.09, 0.3], pos: [0, 0, 0.15], rot: [0.1, 0, 0], color: 'accent' },
          { shape: 'sphere', size: [0.06, 0.06, 0.06], pos: [0, 0, -0.2], rot: [0, 0, 0], color: 'secondary' },
        ],
        animation: 'none',
      },
    },
    sfx: 'railshot',
    unlock: { type: 'buy', cost: 160 },
  },
]);
