// APETATO level-up upgrade pool.
// Rolled on level-up, weighted by `weight` (modified by luck elsewhere).
// ~16 common single-stat (weight 10), ~12 rare dual-stat (weight 5),
// ~8 epic tradeoffs (weight 2), ~4 legendary spikes (weight 1).
// Pure frozen data; statMods keys come from src/core/statmodel.js.

function deepFreeze(obj) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (v && typeof v === 'object') deepFreeze(v);
  }
  return Object.freeze(obj);
}

export const UPGRADES = deepFreeze([
  // --- Common: single stat, weight 10 ---------------------------------------
  {
    id: 'up_muscles',
    name: 'Bigger Muscles',
    rarity: 0,
    weight: 10,
    statMods: { meleeDamage: 3 },
    description: 'You did one push-up. The jungle noticed.',
  },
  {
    id: 'up_aim',
    name: 'Better Aim',
    rarity: 0,
    weight: 10,
    statMods: { rangedDamage: 3 },
    description: 'Close one eye. Not both — we tried both.',
  },
  {
    id: 'up_sparks',
    name: 'Spicy Sparks',
    rarity: 0,
    weight: 10,
    statMods: { elementalDamage: 3 },
    description: 'Your fur crackles with banana-static.',
  },
  {
    id: 'up_gears',
    name: 'Extra Gears',
    rarity: 0,
    weight: 10,
    statMods: { engineering: 3 },
    description: 'You found gears. You ate one. The rest help.',
  },
  {
    id: 'up_haste',
    name: 'Peel Haste',
    rarity: 0,
    weight: 10,
    statMods: { attackSpeed: 3 },
    description: 'Faster hands, same banana.',
  },
  {
    id: 'up_vital',
    name: 'Thicker Hide',
    rarity: 0,
    weight: 10,
    statMods: { maxHp: 3 },
    description: 'Three more HP between you and the compost heap.',
  },
  {
    id: 'up_regen',
    name: 'Banana Regeneration',
    rarity: 0,
    weight: 10,
    statMods: { hpRegen: 2 },
    description: 'Your cells run on potassium now.',
  },
  {
    id: 'up_armor',
    name: 'Bark Plating',
    rarity: 0,
    weight: 10,
    statMods: { armor: 2 },
    description: 'Bark: worse than bite, better than nothing.',
  },
  {
    id: 'up_dodge',
    name: 'Slippery Moves',
    rarity: 0,
    weight: 10,
    statMods: { dodge: 2 },
    description: 'You practiced on your own discarded peels.',
  },
  {
    id: 'up_speed',
    name: 'Quick Feet',
    rarity: 0,
    weight: 10,
    statMods: { speed: 2 },
    description: 'Zoomies, but weaponized.',
  },
  {
    id: 'up_luck',
    name: 'Monkey Fortune',
    rarity: 0,
    weight: 10,
    statMods: { luck: 3 },
    description: 'A fortune cookie told you so.',
  },
  {
    id: 'up_crit',
    name: 'Keen Eye',
    rarity: 0,
    weight: 10,
    statMods: { critChance: 3 },
    description: 'You now see the exact spot marked "bonk here".',
  },
  {
    id: 'up_range',
    name: 'Long Arms',
    rarity: 0,
    weight: 10,
    statMods: { range: 3 },
    description: 'Stretch before reading this.',
  },
  {
    id: 'up_magnet',
    name: 'Grabby Aura',
    rarity: 0,
    weight: 10,
    statMods: { pickupRange: 5 },
    description: 'Loot rolls uphill toward you now.',
  },
  {
    id: 'up_greed',
    name: 'Coin Sniffer',
    rarity: 0,
    weight: 10,
    statMods: { coinGain: 3 },
    description: 'You can smell profit. It smells like bananas.',
  },
  {
    id: 'up_wisdom',
    name: 'Jungle Wisdom',
    rarity: 0,
    weight: 10,
    statMods: { xpGain: 3 },
    description: 'Learn from every bonk, given and received.',
  },

  // --- Rare: dual stat, weight 5 ---------------------------------------------
  {
    id: 'up_bruiser',
    name: 'Bruiser Regimen',
    rarity: 1,
    weight: 5,
    statMods: { meleeDamage: 4, maxHp: 3 },
    description: 'Lift coconuts. Become coconut.',
  },
  {
    id: 'up_sharpshooter',
    name: 'Sharpshooter Diet',
    rarity: 1,
    weight: 5,
    statMods: { rangedDamage: 4, range: 3 },
    description: 'Carrots for the eyes, bananas for the soul.',
  },
  {
    id: 'up_battery',
    name: 'Static Charge',
    rarity: 1,
    weight: 5,
    statMods: { elementalDamage: 4, effectDuration: 8 },
    description: 'Rub feet on carpet. Apply monkey to enemy.',
  },
  {
    id: 'up_tinker',
    name: 'Tinker Session',
    rarity: 1,
    weight: 5,
    statMods: { engineering: 4, attackSpeed: 3 },
    description: 'You voided every warranty you own. Worth it.',
  },
  {
    id: 'up_frenzy',
    name: 'Banana Frenzy',
    rarity: 1,
    weight: 5,
    statMods: { attackSpeed: 5, speed: 2 },
    description: 'Someone said "last banana". It wasn\u2019t. Keep the energy.',
  },
  {
    id: 'up_bulwark',
    name: 'Peel Bulwark',
    rarity: 1,
    weight: 5,
    statMods: { armor: 3, shieldMax: 3 },
    description: 'Layers. Like a banana. Or an onion. But banana.',
  },
  {
    id: 'up_slippery',
    name: 'Greased Reflexes',
    rarity: 1,
    weight: 5,
    statMods: { dodge: 3, speed: 3 },
    description: 'You are legally uncatchable in four jurisdictions.',
  },
  {
    id: 'up_bounty',
    name: 'Bounty Instincts',
    rarity: 1,
    weight: 5,
    statMods: { luck: 4, harvesting: 4 },
    description: 'Every bush owes you something.',
  },
  {
    id: 'up_deadeye',
    name: 'Deadeye Focus',
    rarity: 1,
    weight: 5,
    statMods: { critChance: 3, critDamage: 8 },
    description: 'Blink less. Bonk more.',
  },
  {
    id: 'up_vampiric',
    name: 'Vampiric Appetite',
    rarity: 1,
    weight: 5,
    statMods: { lifesteal: 3, maxHp: 3 },
    description: 'You drink your smoothies... aggressively.',
  },
  {
    id: 'up_scavenger',
    name: 'Scavenger Sense',
    rarity: 1,
    weight: 5,
    statMods: { coinGain: 4, pickupRange: 5 },
    description: 'One ape\u2019s trash is your entire retirement plan.',
  },
  {
    id: 'up_scholar',
    name: 'Peel Scholar',
    rarity: 1,
    weight: 5,
    statMods: { xpGain: 4, luck: 3 },
    description: 'You annotated a banana. Academia weeps with pride.',
  },

  // --- Epic: tradeoffs, weight 2 ----------------------------------------------
  {
    id: 'up_glass_fury',
    name: 'Glass Fury',
    rarity: 2,
    weight: 2,
    statMods: { damagePct: 10, maxHp: -4 },
    description: 'Hit like a truck. Shatter like a windshield.',
  },
  {
    id: 'up_berserk',
    name: 'Berserk Rhythm',
    rarity: 2,
    weight: 2,
    statMods: { attackSpeed: 12, armor: -3 },
    description: 'Defense is a state of mind. You lost the state.',
  },
  {
    id: 'up_bunker',
    name: 'Bunker Mentality',
    rarity: 2,
    weight: 2,
    statMods: { armor: 8, speed: -4 },
    description: 'You are the immovable object. Emphasis on immovable.',
  },
  {
    id: 'up_gambler',
    name: 'Gambler\u2019s Peel',
    rarity: 2,
    weight: 2,
    statMods: { luck: 10, curse: 2 },
    description: 'The house always wins. You brought your own house.',
  },
  {
    id: 'up_juggernaut',
    name: 'Juggernaut Bulk',
    rarity: 2,
    weight: 2,
    statMods: { maxHp: 12, dodge: -4 },
    description: 'Big target, bigger heart, biggest lunch.',
  },
  {
    id: 'up_executioner',
    name: 'Executioner Patience',
    rarity: 2,
    weight: 2,
    statMods: { critDamage: 20, attackSpeed: -5 },
    description: 'Slow hands. Devastating punctuation.',
  },
  {
    id: 'up_hoarder',
    name: 'Hoarder Logic',
    rarity: 2,
    weight: 2,
    statMods: { coinGain: 12, xpGain: -5 },
    description: 'Why learn when you can OWN?',
  },
  {
    id: 'up_stormcaller',
    name: 'Stormcaller Pact',
    rarity: 2,
    weight: 2,
    statMods: { elementalDamage: 10, maxHp: -3 },
    description: 'The storm asked for a small deposit. Of you.',
  },

  // --- Legendary: spikes, weight 1 ---------------------------------------------
  {
    id: 'up_banana_god',
    name: 'Banana God\u2019s Blessing',
    rarity: 3,
    weight: 1,
    statMods: { damagePct: 15 },
    description: 'The Great Banana peeled itself in your honor.',
  },
  {
    id: 'up_gorilla_mode',
    name: 'Gorilla Mode',
    rarity: 3,
    weight: 1,
    statMods: { maxHp: 20, meleeDamage: 5 },
    description: 'You woke up and chose chest-thumping.',
  },
  {
    id: 'up_bullet_time',
    name: 'Bullet Thyme',
    rarity: 3,
    weight: 1,
    statMods: { attackSpeed: 15, dodge: 5 },
    description: 'An herb so fast it seasons the future.',
  },
  {
    id: 'up_golden_destiny',
    name: 'Golden Destiny',
    rarity: 3,
    weight: 1,
    statMods: { luck: 12, coinGain: 10 },
    description: 'A fortune teller looked at your palm and asked for a loan.',
  },
]);
