// APETATO shop items — COMMON (rarity 0).
// Cheap snacks and pocket junk: 1-2 small statMods, prices ~10-16.
// Pure frozen data. Stat keys must be from src/core/statmodel.js STAT_KEYS.

function deepFreeze(obj) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (v && typeof v === 'object') deepFreeze(v);
  }
  return Object.freeze(obj);
}

export const COMMON_ITEMS = deepFreeze([
  {
    id: 'lucky_banana',
    name: 'Lucky Banana',
    description: 'A banana with a four-leaf peel. Statistically implausible, nutritionally excellent.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['banana', 'fruit', 'shiny'],
    statMods: { luck: 3 },
    effects: [],
  },
  {
    id: 'green_banana',
    name: 'Green Banana',
    description: 'Not ripe yet. Neither are you. Grow together.',
    rarity: 0,
    basePrice: 10,
    maxStacks: -1,
    tags: ['banana', 'fruit'],
    statMods: { maxHp: 3 },
    effects: [],
  },
  {
    id: 'banana_bandage',
    name: 'Banana Bandage',
    description: 'A peel wrapped around a boo-boo. Medical science hates this trick.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['banana', 'defense'],
    statMods: { hpRegen: 2 },
    effects: [],
  },
  {
    id: 'fist_wraps',
    name: 'Fist Wraps',
    description: 'Woven from vines and pure grudge. Punching feels artisanal now.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['tool', 'jungle'],
    statMods: { meleeDamage: 3 },
    effects: [],
  },
  {
    id: 'slingshot_rubber',
    name: 'Slingshot Rubber',
    description: 'Stretchier than a monkey excuse. Things you fling fly meaner.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['tool'],
    statMods: { rangedDamage: 3 },
    effects: [],
  },
  {
    id: 'sparkler_peel',
    name: 'Sparkler Peel',
    description: 'A banana peel that never stopped crackling. Do not lick.',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['banana', 'mystic'],
    statMods: { elementalDamage: 3 },
    effects: [],
  },
  {
    id: 'wonder_wrench',
    name: 'Wonder Wrench',
    description: 'Tightens bolts, loosens problems. Smells faintly of banana grease.',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['tool', 'tech'],
    statMods: { engineering: 3 },
    effects: [],
  },
  {
    id: 'jitter_bean',
    name: 'Jitter Bean',
    description: 'Technically a fruit. Technically a heart condition.',
    rarity: 0,
    basePrice: 14,
    maxStacks: -1,
    tags: ['fruit'],
    statMods: { attackSpeed: 4 },
    effects: [],
  },
  {
    id: 'pointy_stick',
    name: 'Pointy Stick',
    description: 'The jungle\u2019s oldest technology. Still undefeated.',
    rarity: 0,
    basePrice: 11,
    maxStacks: -1,
    tags: ['tool', 'jungle'],
    statMods: { meleeDamage: 2, range: 1 },
    effects: [],
  },
  {
    id: 'banana_scope',
    name: 'Banana Scope',
    description: 'Hollowed-out banana. You can see the future through it: bonked enemies.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['banana', 'tech'],
    statMods: { range: 3 },
    effects: [],
  },
  {
    id: 'turtle_shellette',
    name: 'Turtle Shellette',
    description: 'A tiny shell for a tiny amount of not dying.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['defense', 'jungle'],
    statMods: { armor: 2 },
    effects: [],
  },
  {
    id: 'slippery_peel',
    name: 'Slippery Peel',
    description: 'Everyone should watch their step around you. You already did.',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['banana'],
    statMods: { dodge: 3 },
    effects: [],
  },
  {
    id: 'jungle_sandals',
    name: 'Jungle Sandals',
    description: 'Open-toed, closed-minded about standing still.',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['jungle'],
    statMods: { speed: 3 },
    effects: [],
  },
  {
    id: 'shiny_pebble',
    name: 'Shiny Pebble',
    description: 'It sparkles. You feel richer just holding it. Collectors go bananas for a full pocket of shinies.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['shiny'],
    statMods: { luck: 2, coinGain: 2 },
    effects: [],
  },
  {
    id: 'peel_magnet',
    name: 'Peel Magnet',
    description: 'Attracts loot, lint, and long-lost banana stickers.',
    rarity: 0,
    basePrice: 11,
    maxStacks: -1,
    tags: ['banana', 'tech'],
    statMods: { pickupRange: 5 },
    effects: [],
  },
  {
    id: 'smart_glasses',
    name: 'Smart Glasses',
    description: 'No lenses, all confidence. You learn 3% faster and look 100% smugger.',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['tool', 'mystic'],
    statMods: { xpGain: 3 },
    effects: [],
  },
  {
    id: 'banana_bank',
    name: 'Banana Bank',
    description: 'A ceramic banana with a coin slot. Interest rate: yes.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['banana', 'shiny'],
    statMods: { coinGain: 3 },
    effects: [],
  },
  {
    id: 'heavy_coconut',
    name: 'Heavy Coconut',
    description: 'Dense. Like your enemies, right before they meet it.',
    rarity: 0,
    basePrice: 11,
    maxStacks: -1,
    tags: ['fruit', 'jungle'],
    statMods: { knockback: 4 },
    effects: [],
  },
  {
    id: 'greased_groove',
    name: 'Greased Groove',
    description: 'A tin of banana grease for your barrels, bows and bad ideas.',
    rarity: 0,
    basePrice: 11,
    maxStacks: -1,
    tags: ['tool'],
    statMods: { projectileSpeed: 5 },
    effects: [],
  },
  {
    id: 'spicy_pepper',
    name: 'Spicy Pepper',
    description: 'The jungle\u2019s way of saying "no". You say "yes".',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['fruit'],
    statMods: { elementalDamage: 2, attackSpeed: 1 },
    effects: [],
  },
  {
    id: 'meat_snack',
    name: 'Meat Snack',
    description: 'You\u2019re mostly frugivorous. Mostly. Butchers appreciate a dedicated meat shelf.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['meat'],
    statMods: { maxHp: 2, hpRegen: 1 },
    effects: [],
  },
  {
    id: 'thorn_bracelet',
    name: 'Thorn Bracelet',
    description: 'Fashionable, and legally distinct from barbed wire.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['jungle', 'defense'],
    statMods: { thorns: 2 },
    effects: [],
  },
  {
    id: 'bubble_gum_shield',
    name: 'Bubble Gum Shield',
    description: 'Blow a bubble, block a bonk. Banana flavored, obviously.',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['defense'],
    statMods: { shieldMax: 3 },
    effects: [],
  },
  {
    id: 'harvest_gloves',
    name: 'Harvest Gloves',
    description: 'For picking bananas, pockets, and fights.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['tool', 'jungle'],
    statMods: { harvesting: 3 },
    effects: [],
  },
  {
    id: 'crit_seed',
    name: 'Crit Seed',
    description: 'Plant it in your enemies. Watch precision bloom.',
    rarity: 0,
    basePrice: 14,
    maxStacks: -1,
    tags: ['fruit', 'shiny'],
    statMods: { critChance: 2 },
    effects: [],
  },
  {
    id: 'angry_eyebrows',
    name: 'Angry Eyebrows',
    description: 'Stick-on fury. Your crits now carry emotional weight.',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['cursed'],
    statMods: { critDamage: 5 },
    effects: [],
  },
  {
    id: 'split_helmet',
    name: 'Split Helmet',
    description: 'Half a coconut, whole lot of denial about incoming damage.',
    rarity: 0,
    basePrice: 14,
    maxStacks: -1,
    tags: ['defense', 'jungle'],
    statMods: { armor: 2, maxHp: 2 },
    effects: [],
  },
  {
    id: 'mosquito_amulet',
    name: 'Mosquito Amulet',
    description: 'A tiny vampire on a string. It shares. Sometimes.',
    rarity: 0,
    basePrice: 14,
    maxStacks: -1,
    tags: ['cursed', 'jungle'],
    statMods: { lifesteal: 2 },
    effects: [],
  },
  {
    id: 'hustle_drum',
    name: 'Hustle Drum',
    description: 'Boom-tak-boom. Your paws obey the rhythm.',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['tool', 'jungle'],
    statMods: { attackSpeed: 3 },
    effects: [],
  },
  {
    id: 'fig_fanny_pack',
    name: 'Fig Fanny Pack',
    description: 'Emergency figs. For emergencies. Or Tuesdays.',
    rarity: 0,
    basePrice: 11,
    maxStacks: -1,
    tags: ['fruit', 'tool'],
    statMods: { maxHp: 3 },
    effects: [],
  },
  {
    id: 'peel_polish',
    name: 'Peel Polish',
    description: 'Buffs your bananas to a menacing shine. Enemies notice. Briefly.',
    rarity: 0,
    basePrice: 14,
    maxStacks: -1,
    tags: ['banana', 'shiny'],
    statMods: { damagePct: 2 },
    effects: [],
  },
  {
    id: 'tail_extension',
    name: 'Tail Extension',
    description: 'Aftermarket prehensile upgrade. Grabs loot, dodges lawsuits.',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['jungle'],
    statMods: { pickupRange: 3, dodge: 1 },
    effects: [],
  },
  {
    id: 'banana_compass',
    name: 'Banana Compass',
    description: 'Always points toward the nearest banana. Which is you. Very validating.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['banana', 'tool'],
    statMods: { speed: 2, luck: 1 },
    effects: [],
  },
  {
    id: 'pocket_pinecone',
    name: 'Pocket Pinecone',
    description: 'Nature\u2019s brass knuckle. Free splinters included.',
    rarity: 0,
    basePrice: 10,
    maxStacks: -1,
    tags: ['jungle'],
    statMods: { knockback: 2, meleeDamage: 1 },
    effects: [],
  },
  {
    id: 'glowworm_lantern',
    name: 'Glowworm Lantern',
    description: 'A jar of judgmental light. Sees farther than you deserve.',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['jungle', 'mystic'],
    statMods: { range: 2, elementalDamage: 1 },
    effects: [],
  },
  {
    id: 'stump_shield',
    name: 'Stump Shield',
    description: 'A slice of tree. The rings tell a story: "ouch", mostly.',
    rarity: 0,
    basePrice: 14,
    maxStacks: -1,
    tags: ['defense', 'jungle'],
    statMods: { armor: 3 },
    effects: [],
  },
  {
    id: 'banana_gum',
    name: 'Banana Gum',
    description: 'Chew it and everything sticky sticks longer. Science!',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['banana'],
    statMods: { effectDuration: 5 },
    effects: [],
  },
  {
    id: 'copper_cog',
    name: 'Copper Cog',
    description: 'One cog closer to a machine that peels bananas for you.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['tech'],
    statMods: { engineering: 2, armor: 1 },
    effects: [],
  },
  {
    id: 'sugar_cube',
    name: 'Sugar Cube',
    description: 'Pure crystallized zoomies.',
    rarity: 0,
    basePrice: 12,
    maxStacks: -1,
    tags: ['shiny'],
    statMods: { attackSpeed: 2, speed: 1 },
    effects: [],
  },
  {
    id: 'monkey_mitts',
    name: 'Monkey Mitts',
    description: 'Oven mitts repurposed for shoving. The oven forgives you.',
    rarity: 0,
    basePrice: 13,
    maxStacks: -1,
    tags: ['jungle', 'tool'],
    statMods: { meleeDamage: 2, knockback: 2 },
    effects: [],
  },
]);
