// APETATO shop items — EPIC (rarity 2).
// Build-defining effects: onCrit explosions, onDodge economies, interval
// novas, and the statPer tag-scaler family (the deliberate cross-item
// synergies — their descriptions wink about it). Prices ~48-65.

function deepFreeze(obj) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (v && typeof v === 'object') deepFreeze(v);
  }
  return Object.freeze(obj);
}

export const EPIC_ITEMS = deepFreeze([
  // --- Tag scalers: reward hoarding a tag (cross-item synergies) ------------
  {
    id: 'banana_battery',
    name: 'Banana Battery',
    description: 'Runs on potassium. Every banana-tagged trinket you own charges it further. Hoard accordingly. (wink)',
    rarity: 2,
    basePrice: 58,
    maxStacks: 2,
    tags: ['banana', 'tech'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'damagePct', add: 2, max: 20, per: { what: 'itemTag', tag: 'banana' } }] },
    ],
  },
  {
    id: 'smoothie_blender',
    name: 'Smoothie Blender',
    description: 'Blends every fruit item you carry into pure recovery. More fruit, more smoothie. You see where this is going. (wink)',
    rarity: 2,
    basePrice: 55,
    maxStacks: 2,
    tags: ['fruit', 'tech'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'hpRegen', add: 1, max: 8, per: { what: 'itemTag', tag: 'fruit' } }] },
    ],
  },
  {
    id: 'gadget_harness',
    name: 'Gadget Harness',
    description: 'Straps for every gizmo. Each tech item you own makes the harness smarter than you. (wink)',
    rarity: 2,
    basePrice: 56,
    maxStacks: 2,
    tags: ['tech', 'tool'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'engineering', add: 2, max: 16, per: { what: 'itemTag', tag: 'tech' } }] },
    ],
  },
  {
    id: 'magpie_medallion',
    name: 'Magpie Medallion',
    description: 'Ooh, shiny. Each shiny item you own makes your coins breed faster. Keep collecting sparkle. (wink)',
    rarity: 2,
    basePrice: 54,
    maxStacks: 2,
    tags: ['shiny'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'coinGain', add: 3, max: 24, per: { what: 'itemTag', tag: 'shiny' } }] },
    ],
  },
  {
    id: 'carnivore_crown',
    name: 'Carnivore Crown',
    description: 'A crown of tiny bones. Every meat item in your stash thickens your hide. Keep the butcher on speed dial. (wink)',
    rarity: 2,
    basePrice: 57,
    maxStacks: 2,
    tags: ['meat'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'maxHp', add: 3, max: 18, per: { what: 'itemTag', tag: 'meat' } }] },
    ],
  },
  {
    id: 'drum_circle',
    name: 'Drum Circle',
    description: 'The more jungle gear you haul, the harder the beat drops, the faster you go. Stack the canopy. (wink)',
    rarity: 2,
    basePrice: 56,
    maxStacks: 2,
    tags: ['jungle'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'speed', add: 2, max: 12, per: { what: 'itemTag', tag: 'jungle' } }] },
    ],
  },
  {
    id: 'occult_peel',
    name: 'Occult Peel',
    description: 'A peel inscribed with forbidden banana runes. Feeds on every mystic item you own. Collect responsibly. (wink)',
    rarity: 2,
    basePrice: 58,
    maxStacks: 2,
    tags: ['mystic', 'banana'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'elementalDamage', add: 2, max: 16, per: { what: 'itemTag', tag: 'mystic' } }] },
    ],
  },
  {
    id: 'frond_fortress',
    name: 'Frond Fortress',
    description: 'Layered leaf armor that bolts onto every defense item you own. Turtles hate how good you are at this. (wink)',
    rarity: 2,
    basePrice: 57,
    maxStacks: 2,
    tags: ['defense', 'jungle'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'armor', add: 2, max: 14, per: { what: 'itemTag', tag: 'defense' } }] },
    ],
  },
  {
    id: 'doom_toolbox',
    name: 'Doom Toolbox',
    description: 'Each tool you own is another lever to yank mid-fight. More tools, more tempo. (wink)',
    rarity: 2,
    basePrice: 59,
    maxStacks: 2,
    tags: ['tool'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'attackSpeed', add: 2, max: 16, per: { what: 'itemTag', tag: 'tool' } }] },
    ],
  },
  {
    id: 'hex_collection',
    name: 'Hex Collection',
    description: 'A binder of curses. Every cursed item you own adds a page — and a punch. Yes, this is a cry for help. (wink)',
    rarity: 2,
    basePrice: 60,
    maxStacks: 2,
    tags: ['cursed', 'mystic'],
    statMods: { curse: 1 },
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'damagePct', add: 3, max: 18, per: { what: 'itemTag', tag: 'cursed' } }] },
    ],
  },

  // --- Other statPer scalers -------------------------------------------------
  {
    id: 'adrenal_glands',
    name: 'Adrenal Glands',
    description: 'Bottled panic. The closer to the drain you circle, the harder you hit.',
    rarity: 2,
    basePrice: 60,
    maxStacks: 2,
    tags: ['meat', 'cursed'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'damagePct', add: 2, max: 30, per: { what: 'missingHpPct', step: 5 } }] },
    ],
  },
  {
    id: 'wave_rider_totem',
    name: 'Wave Rider Totem',
    description: 'Grows a ring of bark every wave you survive. Trees get it.',
    rarity: 2,
    basePrice: 55,
    maxStacks: 2,
    tags: ['mystic', 'jungle'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'maxHp', add: 1, max: 20, per: { what: 'wave', step: 1 } }] },
    ],
  },
  {
    id: 'trophy_necklace',
    name: 'Trophy Necklace',
    description: 'A bead per fifty bonks. It gets heavy. So do your hits.',
    rarity: 2,
    basePrice: 62,
    maxStacks: 2,
    tags: ['cursed', 'jungle'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'damagePct', add: 1, max: 15, per: { what: 'kills', step: 50 } }] },
    ],
  },
  {
    id: 'quartermaster_peel',
    name: 'Quartermaster Peel',
    description: 'Files requisition forms for every ranged weapon you field. Bureaucracy, but it slaps. (wink)',
    rarity: 2,
    basePrice: 56,
    maxStacks: 2,
    tags: ['banana', 'tool'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'rangedDamage', add: 3, max: 18, per: { what: 'weaponClass', cls: 'ranged' } }] },
    ],
  },
  {
    id: 'dojo_membership',
    name: 'Dojo Membership',
    description: 'Every melee weapon you carry counts as a black belt. The dojo mails you power. (wink)',
    rarity: 2,
    basePrice: 56,
    maxStacks: 2,
    tags: ['jungle', 'tool'],
    statMods: {},
    effects: [
      { trigger: 'passive', do: [{ op: 'statPer', stat: 'meleeDamage', add: 3, max: 18, per: { what: 'weaponClass', cls: 'melee' } }] },
    ],
  },

  // --- Build-defining triggered effects --------------------------------------
  {
    id: 'crit_bomb_gland',
    name: 'Crit Bomb Gland',
    description: 'A gland that interprets critical hits as fireworks requests.',
    rarity: 2,
    basePrice: 62,
    maxStacks: -1,
    tags: ['cursed', 'tool'],
    statMods: { critChance: 3 },
    effects: [
      { trigger: 'onCrit', chance: 25, do: [{ op: 'explode', damage: 8, radius: 2.5, scaled: true, at: 'target' }] },
    ],
  },
  {
    id: 'dodge_dividends',
    name: 'Dodge Dividends',
    description: 'Financial advice from a mongoose: never get hit, always get paid.',
    rarity: 2,
    basePrice: 58,
    maxStacks: -1,
    tags: ['shiny', 'jungle'],
    statMods: { dodge: 3 },
    effects: [
      { trigger: 'onDodge', do: [{ op: 'coins', amount: 2 }] },
    ],
  },
  {
    id: 'nova_peel',
    name: 'Nova Peel',
    description: 'Every few seconds it remembers it\u2019s a star and detonates about it.',
    rarity: 2,
    basePrice: 60,
    maxStacks: -1,
    tags: ['banana', 'mystic'],
    statMods: {},
    effects: [
      { trigger: 'interval', interval: 6, do: [{ op: 'explode', damage: 10, radius: 3, scaled: true, at: 'self' }] },
    ],
  },
  {
    id: 'storm_totem',
    name: 'Storm Totem',
    description: 'A tiny idol with big opinions about weather. Zaps the neighborhood on schedule.',
    rarity: 2,
    basePrice: 61,
    maxStacks: -1,
    tags: ['mystic', 'tech'],
    statMods: {},
    effects: [
      { trigger: 'interval', interval: 5, do: [{ op: 'status', status: 'shock', dps: 5, duration: 1.5, target: 'area', radius: 4 }] },
    ],
  },
  {
    id: 'sentry_bunch',
    name: 'Sentry Bunch',
    description: 'A bunch of bananas that took a security seminar. Deploys itself every wave.',
    rarity: 2,
    basePrice: 64,
    maxStacks: 2,
    tags: ['tech', 'banana'],
    statMods: {},
    effects: [
      { trigger: 'onWaveStart', do: [{ op: 'summon', what: 'banana_turret', max: 1 }] },
    ],
  },
  {
    id: 'molotov_smoothie',
    name: 'Molotov Smoothie',
    description: 'Flambéed fruit. Fallen enemies occasionally combust into ambience.',
    rarity: 2,
    basePrice: 59,
    maxStacks: -1,
    tags: ['fruit', 'cursed'],
    statMods: {},
    effects: [
      { trigger: 'onKill', chance: 15, do: [{ op: 'status', status: 'burn', dps: 4, duration: 3, target: 'area', radius: 2 }] },
    ],
  },
  {
    id: 'venom_gland',
    name: 'Venom Gland',
    description: 'Borrowed from a frog who owed you money.',
    rarity: 2,
    basePrice: 58,
    maxStacks: -1,
    tags: ['jungle', 'cursed'],
    statMods: {},
    effects: [
      { trigger: 'onHit', chance: 20, do: [{ op: 'status', status: 'poison', dps: 3, duration: 3, target: 'target' }] },
    ],
  },
  {
    id: 'frost_banana',
    name: 'Frost Banana',
    description: 'Straight from the freezer of destiny. Occasionally flash-freezes whoever you slap.',
    rarity: 2,
    basePrice: 61,
    maxStacks: -1,
    tags: ['banana', 'mystic'],
    statMods: {},
    effects: [
      { trigger: 'onHit', chance: 10, do: [{ op: 'status', status: 'freeze', dps: 0, duration: 1, target: 'target' }] },
    ],
  },
  {
    id: 'second_wind_whistle',
    name: 'Second Wind Whistle',
    description: 'Blow it at death\u2019s door and sprint out the window instead.',
    rarity: 2,
    basePrice: 60,
    maxStacks: 3,
    tags: ['jungle', 'tool'],
    statMods: {},
    effects: [
      {
        trigger: 'onLowHp',
        do: [
          { op: 'heal', amount: 8 },
          { op: 'buff', stat: 'speed', add: 20, duration: 3 },
        ],
      },
    ],
  },
  {
    id: 'coin_cannon',
    name: 'Coin Cannon',
    description: 'Sometimes fires the money you pick up at the nearest problem. Pays interest if you also bank bananas. (wink)',
    rarity: 2,
    basePrice: 62,
    maxStacks: -1,
    tags: ['shiny', 'tech'],
    statMods: {},
    effects: [
      { trigger: 'onPickupCoin', chance: 10, do: [{ op: 'projectile', visual: 'coin', damage: 8, count: 1, speed: 14, scaled: true }] },
      { trigger: 'onPickupCoin', chance: 5, cond: { hasTag: 'banana' }, do: [{ op: 'coins', amount: 1 }] },
    ],
  },
  {
    id: 'xp_resonator',
    name: 'XP Resonator',
    description: 'Echoes knowledge back at you. Double-dips into the wisdom buffet.',
    rarity: 2,
    basePrice: 63,
    maxStacks: -1,
    tags: ['mystic', 'tech'],
    statMods: {},
    effects: [
      { trigger: 'onPickupXp', chance: 10, do: [{ op: 'xp', amount: 1 }] },
    ],
  },
  {
    id: 'shield_capacitor',
    name: 'Shield Capacitor',
    description: 'Front-loads your personal bubble every wave. Pop-proof for the first few seconds of chaos.',
    rarity: 2,
    basePrice: 60,
    maxStacks: -1,
    tags: ['tech', 'defense'],
    statMods: { shieldMax: 5 },
    effects: [
      { trigger: 'onWaveStart', do: [{ op: 'shield', amount: 10 }] },
    ],
  },
  {
    id: 'cactus_riposte',
    name: 'Cactus Riposte',
    description: 'Hug me once, shame on you. There is no second hug.',
    rarity: 2,
    basePrice: 58,
    maxStacks: -1,
    tags: ['jungle', 'defense'],
    statMods: { thorns: 3 },
    effects: [
      { trigger: 'onTakeDamage', do: [{ op: 'damageNearest', damage: 10, radius: 3, scaled: true }] },
    ],
  },
  {
    id: 'executioner_peel',
    name: 'Executioner Peel',
    description: 'Each kill whispers "again". You listen.',
    rarity: 2,
    basePrice: 61,
    maxStacks: -1,
    tags: ['cursed', 'banana'],
    statMods: {},
    effects: [
      { trigger: 'onKill', chance: 8, do: [{ op: 'buff', stat: 'damagePct', add: 10, duration: 4 }] },
    ],
  },
  {
    id: 'levelup_fireworks',
    name: 'Level-Up Fireworks',
    description: 'Celebrates your personal growth by redistributing everyone nearby.',
    rarity: 2,
    basePrice: 57,
    maxStacks: -1,
    tags: ['shiny', 'tool'],
    statMods: {},
    effects: [
      { trigger: 'onLevelUp', do: [{ op: 'explode', damage: 15, radius: 4, scaled: true, at: 'self' }] },
    ],
  },
  {
    id: 'shop_rat',
    name: 'Shop Rat',
    description: 'Lives in the shop walls. Slides you a few coins every visit. Don\u2019t ask where from.',
    rarity: 2,
    basePrice: 65,
    maxStacks: 3,
    tags: ['meat', 'shiny'],
    statMods: {},
    effects: [
      { trigger: 'onShopEnter', do: [{ op: 'coins', amount: 6 }] },
    ],
  },
  {
    id: 'leech_totem',
    name: 'Leech Totem',
    description: 'Periodically bites the nearest enemy and mails you the juice.',
    rarity: 2,
    basePrice: 63,
    maxStacks: -1,
    tags: ['cursed', 'mystic'],
    statMods: {},
    effects: [
      {
        trigger: 'interval',
        interval: 3,
        do: [
          { op: 'damageNearest', damage: 5, radius: 4, scaled: true },
          { op: 'heal', amount: 1 },
        ],
      },
    ],
  },
  {
    id: 'bleeding_edge',
    name: 'Bleeding Edge',
    description: 'State-of-the-art sharpness. Crits leave a lasting impression.',
    rarity: 2,
    basePrice: 60,
    maxStacks: -1,
    tags: ['tool', 'cursed'],
    statMods: { critDamage: 8 },
    effects: [
      { trigger: 'onCrit', chance: 40, do: [{ op: 'status', status: 'bleed', dps: 4, duration: 3, target: 'target' }] },
    ],
  },
  {
    id: 'panic_button',
    name: 'Panic Button',
    description: 'Big red button. Pressing it is involuntary and so is your attacker\u2019s nap.',
    rarity: 2,
    basePrice: 59,
    maxStacks: -1,
    tags: ['tech', 'defense'],
    statMods: {},
    effects: [
      { trigger: 'onTakeDamage', chance: 20, do: [{ op: 'status', status: 'stun', dps: 0, duration: 0.8, target: 'attacker' }] },
    ],
  },
  {
    id: 'grape_grenades',
    name: 'Grape Grenades',
    description: 'Sun-dried ordnance. Opens every wave with a fruit salvo.',
    rarity: 2,
    basePrice: 58,
    maxStacks: -1,
    tags: ['fruit', 'tool'],
    statMods: {},
    effects: [
      { trigger: 'onWaveStart', do: [{ op: 'projectile', visual: 'grape', damage: 10, count: 6, speed: 10, scaled: true }] },
    ],
  },
]);
