// APETATO shop items — LEGENDARY (rarity 3).
// Rule-benders: huge stat swings with real tradeoffs, weird triggers.
// Prices ~85-110. All maxStacks 1 — one legend per legend.

function deepFreeze(obj) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (v && typeof v === 'object') deepFreeze(v);
  }
  return Object.freeze(obj);
}

export const LEGENDARY_ITEMS = deepFreeze([
  {
    id: 'phantom_peel',
    name: 'Phantom Peel',
    description: 'You are 15% not there. The 85% that remains bruises easily.',
    rarity: 3,
    basePrice: 100,
    maxStacks: 1,
    tags: ['banana', 'mystic'],
    statMods: { dodge: 15, armor: -5 },
    effects: [],
  },
  {
    id: 'hydra_bunch',
    name: 'Hydra Bunch',
    description: 'Peel one banana, two more appear. Each is... noticeably diluted.',
    rarity: 3,
    basePrice: 105,
    maxStacks: 1,
    tags: ['banana', 'cursed'],
    statMods: { extraProjectiles: 1, damagePct: -30 },
    effects: [],
  },
  {
    id: 'gorilla_heart',
    name: 'Gorilla Heart',
    description: 'Donated by a very generous, very large friend. Beats slow. Beats HARD.',
    rarity: 3,
    basePrice: 95,
    maxStacks: 1,
    tags: ['meat', 'jungle'],
    statMods: { maxHp: 25, speed: -8 },
    effects: [],
  },
  {
    id: 'chrono_banana',
    name: 'Chrono Banana',
    description: 'Ripens backwards through time. You attack tomorrow\u2019s speed with yesterday\u2019s body.',
    rarity: 3,
    basePrice: 108,
    maxStacks: 1,
    tags: ['banana', 'mystic'],
    statMods: { attackSpeed: 25, maxHp: -8 },
    effects: [],
  },
  {
    id: 'midas_paw',
    name: 'Midas Paw',
    description: 'Everything you touch turns to gold, including your report card.',
    rarity: 3,
    basePrice: 100,
    maxStacks: 1,
    tags: ['shiny', 'cursed'],
    statMods: { coinGain: 20, xpGain: -8 },
    effects: [
      { trigger: 'onPickupCoin', chance: 5, do: [{ op: 'coins', amount: 1 }] },
    ],
  },
  {
    id: 'sage_skull',
    name: 'Sage Skull',
    description: 'A wise old skull. Tutors you nightly, invoices your wallet.',
    rarity: 3,
    basePrice: 100,
    maxStacks: 1,
    tags: ['mystic', 'cursed'],
    statMods: { xpGain: 20, coinGain: -8 },
    effects: [],
  },
  {
    id: 'glass_banana',
    name: 'Glass Banana',
    description: 'Beautiful. Deadly. One firm handshake from tragedy.',
    rarity: 3,
    basePrice: 110,
    maxStacks: 1,
    tags: ['banana', 'shiny'],
    statMods: { critChance: 12, critDamage: 30, maxHp: -10 },
    effects: [],
  },
  {
    id: 'juggernaut_plate',
    name: 'Juggernaut Plate',
    description: 'You are now a wall. Walls famously do not dodge.',
    rarity: 3,
    basePrice: 98,
    maxStacks: 1,
    tags: ['defense'],
    statMods: { armor: 12, thorns: 8, dodge: -10, speed: -5 },
    effects: [],
  },
  {
    id: 'cloak_of_peels',
    name: 'Cloak of Peels',
    description: 'A cape of overlapping peels. At every wave\u2019s start, you\u2019re basically a rumor.',
    rarity: 3,
    basePrice: 96,
    maxStacks: 1,
    tags: ['banana', 'jungle'],
    statMods: { dodge: 5 },
    effects: [
      { trigger: 'onWaveStart', do: [{ op: 'buff', stat: 'dodge', add: 30, duration: 5 }] },
    ],
  },
  {
    id: 'vampiric_crown',
    name: 'Vampiric Crown',
    description: 'Rule the night. Room service is whoever you\u2019re fighting.',
    rarity: 3,
    basePrice: 105,
    maxStacks: 1,
    tags: ['cursed', 'meat'],
    statMods: { lifesteal: 10, hpRegen: -2 },
    effects: [
      { trigger: 'onKill', chance: 20, do: [{ op: 'heal', amount: 2 }] },
    ],
  },
  {
    id: 'orbital_peel_laser',
    name: 'Orbital Peel Laser',
    description: 'Somewhere above the canopy, a satellite made of peels takes your requests.',
    rarity: 3,
    basePrice: 110,
    maxStacks: 1,
    tags: ['tech', 'banana'],
    statMods: {},
    effects: [
      { trigger: 'interval', interval: 8, do: [{ op: 'damageNearest', damage: 30, radius: 12, scaled: true }] },
    ],
  },
  {
    id: 'bananarang_engine',
    name: 'Bananarang Engine',
    description: 'Some hits spin off bonus bananarangs. Physics filed a complaint; it was returned to sender.',
    rarity: 3,
    basePrice: 107,
    maxStacks: 1,
    tags: ['banana', 'tech'],
    statMods: {},
    effects: [
      { trigger: 'onHit', chance: 8, do: [{ op: 'projectile', visual: 'peel', damage: 12, count: 2, speed: 16, scaled: true }] },
    ],
  },
  {
    id: 'curse_magnet',
    name: 'Curse Magnet',
    description: 'Attracts misfortune, then invoices it. Deep-wave insurance included.',
    rarity: 3,
    basePrice: 102,
    maxStacks: 1,
    tags: ['cursed', 'shiny'],
    statMods: { curse: 5, luck: 10, damagePct: 10 },
    effects: [
      { trigger: 'onWaveStart', cond: { waveGte: 5 }, do: [{ op: 'coins', amount: 5 }] },
    ],
  },
  {
    id: 'pocket_volcano',
    name: 'Pocket Volcano',
    description: 'Travel-size geology. Erupts on a schedule only it respects.',
    rarity: 3,
    basePrice: 104,
    maxStacks: 1,
    tags: ['jungle', 'cursed'],
    statMods: {},
    effects: [
      { trigger: 'interval', interval: 7, do: [{ op: 'explode', damage: 25, radius: 4.5, scaled: true, at: 'nearest' }] },
    ],
  },
  {
    id: 'turtle_emperor_shell',
    name: 'Turtle Emperor Shell',
    description: 'The emperor abdicated; the shell kept ruling. Getting hit files you under "protected".',
    rarity: 3,
    basePrice: 97,
    maxStacks: 1,
    tags: ['defense', 'jungle'],
    statMods: { armor: 8, attackSpeed: -10 },
    effects: [
      { trigger: 'onTakeDamage', do: [{ op: 'shield', amount: 3 }] },
    ],
  },
  {
    id: 'ghost_pepper_extract',
    name: 'Ghost Pepper Extract',
    description: 'Haunted AND spicy. Your hits occasionally catch feelings. And fire.',
    rarity: 3,
    basePrice: 106,
    maxStacks: 1,
    tags: ['fruit', 'cursed'],
    statMods: { elementalDamage: 15, maxHp: -5 },
    effects: [
      { trigger: 'onHit', chance: 15, do: [{ op: 'status', status: 'burn', dps: 5, duration: 2, target: 'target' }] },
    ],
  },
  {
    id: 'monkey_king_sigil',
    name: 'Monkey King Sigil',
    description: 'An ancient pact: one spirit monkey reports for duty each wave. It does not do dishes.',
    rarity: 3,
    basePrice: 108,
    maxStacks: 1,
    tags: ['mystic', 'jungle'],
    statMods: {},
    effects: [
      { trigger: 'onWaveStart', do: [{ op: 'summon', what: 'spirit_monkey', max: 1 }] },
    ],
  },
  {
    id: 'golden_hook',
    name: 'Golden Hook',
    description: 'Harvests everything not nailed down, plus a stipend. Slightly cumbersome.',
    rarity: 3,
    basePrice: 99,
    maxStacks: 1,
    tags: ['shiny', 'tool'],
    statMods: { harvesting: 15, speed: -3 },
    effects: [
      { trigger: 'onWaveEnd', do: [{ op: 'coins', amount: 10 }] },
    ],
  },
  {
    id: 'overgrowth_idol',
    name: 'Overgrowth Idol',
    description: 'The jungle grows through you. Vines everywhere. Punching is now gardening.',
    rarity: 3,
    basePrice: 93,
    maxStacks: 1,
    tags: ['jungle', 'mystic'],
    statMods: { hpRegen: 6, effectDuration: 25, damagePct: -10 },
    effects: [],
  },
  {
    id: 'railgun_peel',
    name: 'Railgun Peel',
    description: 'Electromagnetically accelerated banana skin. Reload time: contemplative.',
    rarity: 3,
    basePrice: 103,
    maxStacks: 1,
    tags: ['tech', 'banana'],
    statMods: { range: 15, projectileSpeed: 25, attackSpeed: -8 },
    effects: [],
  },
  {
    id: 'blood_pact',
    name: 'Blood Pact',
    description: 'You signed in smoothie. The fine print signs back.',
    rarity: 3,
    basePrice: 110,
    maxStacks: 1,
    tags: ['cursed', 'meat'],
    statMods: { damagePct: 25, hpRegen: -3, curse: 2 },
    effects: [],
  },
  {
    id: 'lucky_lucky_banana',
    name: 'Lucky Lucky Banana',
    description: 'So lucky it loops back around to suspicious. Kills sometimes tip you.',
    rarity: 3,
    basePrice: 101,
    maxStacks: 1,
    tags: ['banana', 'shiny'],
    statMods: { luck: 18 },
    effects: [
      { trigger: 'onKill', chance: 5, do: [{ op: 'coins', amount: 2 }] },
    ],
  },
  {
    id: 'stampede_drums',
    name: 'Stampede Drums',
    description: 'When they boom, the whole arena remembers it has legs.',
    rarity: 3,
    basePrice: 94,
    maxStacks: 1,
    tags: ['jungle'],
    statMods: { speed: 15, knockback: 8 },
    effects: [
      { trigger: 'onWaveStart', do: [{ op: 'buff', stat: 'speed', add: 25, duration: 4 }] },
    ],
  },
  {
    id: 'architect_helmet',
    name: 'Architect Helmet',
    description: 'You dream in blueprints now. A scrap turret assembles itself each wave; your own fists feel obsolete.',
    rarity: 3,
    basePrice: 109,
    maxStacks: 1,
    tags: ['tech', 'tool'],
    statMods: { engineering: 15, damagePct: -10 },
    effects: [
      { trigger: 'onWaveStart', do: [{ op: 'summon', what: 'scrap_turret', max: 1 }] },
    ],
  },
  {
    id: 'mirror_peel',
    name: 'Mirror Peel',
    description: 'Reflects bad intentions as pointy shards. Also great for checking your fur.',
    rarity: 3,
    basePrice: 102,
    maxStacks: 1,
    tags: ['shiny', 'mystic'],
    statMods: { thorns: 5 },
    effects: [
      { trigger: 'onTakeDamage', chance: 30, do: [{ op: 'projectile', visual: 'mirror_shard', damage: 15, count: 3, speed: 14, scaled: true }] },
    ],
  },
]);
