// APETATO shop items — RARE (rarity 1).
// 2-3 statMods (about a third carry a negative tradeoff) or one simple
// effect. Prices ~22-32. Pure frozen data; effects use the DSL from
// src/game/effects.js.

function deepFreeze(obj) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (v && typeof v === 'object') deepFreeze(v);
  }
  return Object.freeze(obj);
}

export const RARE_ITEMS = deepFreeze([
  // --- Clean stat bundles ---------------------------------------------------
  {
    id: 'ripe_banana_bundle',
    name: 'Ripe Banana Bundle',
    description: 'Five perfect bananas. You cry a little. Then you thrive.',
    rarity: 1,
    basePrice: 24,
    maxStacks: -1,
    tags: ['banana', 'fruit'],
    statMods: { maxHp: 4, hpRegen: 2 },
    effects: [],
  },
  {
    id: 'monkey_knuckles',
    name: 'Monkey Knuckles',
    description: 'Carved hardwood. Every punch sounds like applause.',
    rarity: 1,
    basePrice: 28,
    maxStacks: -1,
    tags: ['tool', 'jungle'],
    statMods: { meleeDamage: 5, attackSpeed: 3 },
    effects: [],
  },
  {
    id: 'longshot_peel',
    name: 'Longshot Peel',
    description: 'Aerodynamically perfect peel. NASA called; you hung up.',
    rarity: 1,
    basePrice: 28,
    maxStacks: -1,
    tags: ['banana', 'tool'],
    statMods: { rangedDamage: 5, range: 3 },
    effects: [],
  },
  {
    id: 'static_fur',
    name: 'Static Fur',
    description: 'You rubbed a balloon once. The balloon lost.',
    rarity: 1,
    basePrice: 27,
    maxStacks: -1,
    tags: ['mystic', 'jungle'],
    statMods: { elementalDamage: 5, effectDuration: 5 },
    effects: [],
  },
  {
    id: 'gearhead_goggles',
    name: 'Gearhead Goggles',
    description: 'See the world as it truly is: unassembled banana machines.',
    rarity: 1,
    basePrice: 26,
    maxStacks: -1,
    tags: ['tech', 'tool'],
    statMods: { engineering: 5, range: 2 },
    effects: [],
  },
  {
    id: 'golden_pebble',
    name: 'Golden Pebble',
    description: 'The shiny pebble\u2019s rich uncle. Shiny hoarders, rejoice.',
    rarity: 1,
    basePrice: 26,
    maxStacks: -1,
    tags: ['shiny'],
    statMods: { luck: 4, coinGain: 4 },
    effects: [],
  },
  {
    id: 'kevlar_peel',
    name: 'Kevlar Peel',
    description: 'Bulletproof banana skin. The banana inside remains delicious.',
    rarity: 1,
    basePrice: 27,
    maxStacks: -1,
    tags: ['banana', 'defense'],
    statMods: { armor: 4, maxHp: 3 },
    effects: [],
  },
  {
    id: 'acrobat_anklets',
    name: 'Acrobat Anklets',
    description: 'Jingle jingle, missed me.',
    rarity: 1,
    basePrice: 28,
    maxStacks: -1,
    tags: ['jungle'],
    statMods: { dodge: 4, speed: 3 },
    effects: [],
  },
  {
    id: 'vulture_eye',
    name: 'Vulture Eye',
    description: 'Sees weak points. Also sees you eating that third banana. No judgment.',
    rarity: 1,
    basePrice: 30,
    maxStacks: -1,
    tags: ['cursed', 'shiny'],
    statMods: { critChance: 4, critDamage: 8 },
    effects: [],
  },
  {
    id: 'magnet_helmet',
    name: 'Magnet Helmet',
    description: 'Attracts orbs, coins, and mild embarrassment.',
    rarity: 1,
    basePrice: 25,
    maxStacks: -1,
    tags: ['tech'],
    statMods: { pickupRange: 8, xpGain: 3 },
    effects: [],
  },
  {
    id: 'harvester_rake',
    name: 'Harvester Rake',
    description: 'Rakes in leaves, loot, and lifestyle improvements.',
    rarity: 1,
    basePrice: 26,
    maxStacks: -1,
    tags: ['tool', 'jungle'],
    statMods: { harvesting: 5, coinGain: 2 },
    effects: [],
  },
  {
    id: 'meat_kebab',
    name: 'Meat Kebab',
    description: 'Protein tower. Your inner carnivore files the paperwork.',
    rarity: 1,
    basePrice: 28,
    maxStacks: -1,
    tags: ['meat'],
    statMods: { maxHp: 5, lifesteal: 2 },
    effects: [],
  },
  {
    id: 'shield_dynamo',
    name: 'Shield Dynamo',
    description: 'Hums politely while generating a personal-space field.',
    rarity: 1,
    basePrice: 27,
    maxStacks: -1,
    tags: ['tech', 'defense'],
    statMods: { shieldMax: 5, armor: 2 },
    effects: [],
  },
  {
    id: 'jungle_warpaint',
    name: 'Jungle Warpaint',
    description: 'Mashed berries in aggressive stripes. Enemies respect the aesthetic.',
    rarity: 1,
    basePrice: 29,
    maxStacks: -1,
    tags: ['jungle'],
    statMods: { damagePct: 4, knockback: 3 },
    effects: [],
  },
  {
    id: 'twig_quiver',
    name: 'Twig Quiver',
    description: 'Loaded with the pointiest twigs the canopy could legally provide.',
    rarity: 1,
    basePrice: 25,
    maxStacks: -1,
    tags: ['tool', 'jungle'],
    statMods: { projectileSpeed: 8, rangedDamage: 3 },
    effects: [],
  },

  // --- Tradeoffs (a negative statMod each) ----------------------------------
  {
    id: 'overripe_banana',
    name: 'Overripe Banana',
    description: 'Brown, furious, fermented. Hits like regret, slows you like brunch.',
    rarity: 1,
    basePrice: 26,
    maxStacks: -1,
    tags: ['banana', 'fruit', 'cursed'],
    statMods: { damagePct: 6, speed: -2 },
    effects: [],
  },
  {
    id: 'lead_underpants',
    name: 'Lead Underpants',
    description: 'Absolute protection. Absolute waddle.',
    rarity: 1,
    basePrice: 27,
    maxStacks: -1,
    tags: ['defense'],
    statMods: { armor: 6, dodge: -3 },
    effects: [],
  },
  {
    id: 'berserk_pepper',
    name: 'Berserk Pepper',
    description: 'Eat it and swing faster. Your skin? A suggestion now.',
    rarity: 1,
    basePrice: 29,
    maxStacks: -1,
    tags: ['fruit', 'cursed'],
    statMods: { attackSpeed: 8, armor: -2 },
    effects: [],
  },
  {
    id: 'glass_fang',
    name: 'Glass Fang',
    description: 'Devastating. Fragile. Relatable.',
    rarity: 1,
    basePrice: 30,
    maxStacks: -1,
    tags: ['shiny', 'cursed'],
    statMods: { critDamage: 15, maxHp: -3 },
    effects: [],
  },
  {
    id: 'espresso_slug',
    name: 'Espresso Slug',
    description: 'A slug that drank your espresso. Now it drags you around at mach snail.',
    rarity: 1,
    basePrice: 26,
    maxStacks: -1,
    tags: ['jungle', 'cursed'],
    statMods: { speed: 6, hpRegen: -1 },
    effects: [],
  },
  {
    id: 'greedy_paws',
    name: 'Greedy Paws',
    description: 'Grabby little mittens. They skim coins and skip class.',
    rarity: 1,
    basePrice: 28,
    maxStacks: -1,
    tags: ['shiny', 'cursed'],
    statMods: { coinGain: 8, xpGain: -3 },
    effects: [],
  },
  {
    id: 'bookworm_banana',
    name: 'Bookworm Banana',
    description: 'A banana that reads. It bills you for tuition.',
    rarity: 1,
    basePrice: 28,
    maxStacks: -1,
    tags: ['banana', 'mystic'],
    statMods: { xpGain: 8, coinGain: -3 },
    effects: [],
  },
  {
    id: 'spiked_collar',
    name: 'Spiked Collar',
    description: 'Very metal. Slightly restricts your neck-based evasion.',
    rarity: 1,
    basePrice: 27,
    maxStacks: -1,
    tags: ['cursed', 'defense'],
    statMods: { thorns: 5, dodge: -2 },
    effects: [],
  },
  {
    id: 'sniper_peel',
    name: 'Sniper Peel',
    description: 'Breathe. Aim. Peel. Repeat, slowly.',
    rarity: 1,
    basePrice: 29,
    maxStacks: -1,
    tags: ['banana', 'tool'],
    statMods: { range: 8, attackSpeed: -3 },
    effects: [],
  },
  {
    id: 'anvil_backpack',
    name: 'Anvil Backpack',
    description: 'Everything you hit goes flying. Everywhere you go takes a while.',
    rarity: 1,
    basePrice: 25,
    maxStacks: -1,
    tags: ['tool'],
    statMods: { knockback: 8, speed: -3 },
    effects: [],
  },
  {
    id: 'cursed_doubloon',
    name: 'Cursed Doubloon',
    description: 'Heads you win, tails the jungle wins. It\u2019s always both.',
    rarity: 1,
    basePrice: 30,
    maxStacks: -1,
    tags: ['shiny', 'cursed'],
    statMods: { luck: 6, curse: 2 },
    effects: [],
  },
  {
    id: 'vampire_fang',
    name: 'Vampire Fang',
    description: 'One dainty fang. It sips. You wince.',
    rarity: 1,
    basePrice: 30,
    maxStacks: -1,
    tags: ['cursed', 'meat'],
    statMods: { lifesteal: 5, maxHp: -2 },
    effects: [],
  },
  {
    id: 'overclocked_servo',
    name: 'Overclocked Servo',
    description: 'Runs hot. So do you, apparently. Drink water.',
    rarity: 1,
    basePrice: 29,
    maxStacks: -1,
    tags: ['tech', 'cursed'],
    statMods: { engineering: 7, hpRegen: -1 },
    effects: [],
  },

  // --- One simple effect each -----------------------------------------------
  {
    id: 'snack_stash',
    name: 'Snack Stash',
    description: 'A secret pouch of banana chips. Wave over? Crunch time.',
    rarity: 1,
    basePrice: 26,
    maxStacks: -1,
    tags: ['meat', 'defense'],
    statMods: { maxHp: 2 },
    effects: [
      { trigger: 'onWaveEnd', do: [{ op: 'heal', amount: 3 }] },
    ],
  },
  {
    id: 'tip_jar',
    name: 'Tip Jar',
    description: 'The arena appreciates your service. Gratuity not optional.',
    rarity: 1,
    basePrice: 28,
    maxStacks: -1,
    tags: ['shiny', 'tool'],
    statMods: {},
    effects: [
      { trigger: 'onWaveEnd', do: [{ op: 'coins', amount: 4 }] },
    ],
  },
  {
    id: 'bee_buddy',
    name: 'Bee Buddy',
    description: 'A freelance bee. Stings whoever\u2019s closest, invoices in honey.',
    rarity: 1,
    basePrice: 30,
    maxStacks: -1,
    tags: ['jungle'],
    statMods: {},
    effects: [
      { trigger: 'interval', interval: 4, do: [{ op: 'damageNearest', damage: 4, radius: 6, scaled: true }] },
    ],
  },
  {
    id: 'static_peel',
    name: 'Static Peel',
    description: 'Touch the monkey, get the zap. House rules.',
    rarity: 1,
    basePrice: 29,
    maxStacks: -1,
    tags: ['banana', 'mystic'],
    statMods: {},
    effects: [
      { trigger: 'onTakeDamage', chance: 30, do: [{ op: 'status', status: 'shock', dps: 5, duration: 1, target: 'attacker' }] },
    ],
  },
  {
    id: 'second_breakfast',
    name: 'Second Breakfast',
    description: 'A pre-wave banana. Tradition. Also medicine.',
    rarity: 1,
    basePrice: 25,
    maxStacks: -1,
    tags: ['meat', 'fruit'],
    statMods: {},
    effects: [
      { trigger: 'onWaveStart', do: [{ op: 'heal', amount: 4 }] },
    ],
  },
  {
    id: 'sticky_sap_vial',
    name: 'Sticky Sap Vial',
    description: 'Tree syrup with commitment issues: it never lets go.',
    rarity: 1,
    basePrice: 28,
    maxStacks: -1,
    tags: ['jungle'],
    statMods: {},
    effects: [
      { trigger: 'onHit', chance: 10, do: [{ op: 'status', status: 'slow', dps: 0, duration: 1.5, target: 'target' }] },
    ],
  },
  {
    id: 'firecracker_bunch',
    name: 'Firecracker Bunch',
    description: 'Bananas with fuses. Sometimes the punchline explodes.',
    rarity: 1,
    basePrice: 31,
    maxStacks: -1,
    tags: ['banana', 'tool'],
    statMods: {},
    effects: [
      { trigger: 'onKill', chance: 10, do: [{ op: 'explode', damage: 6, radius: 2.5, scaled: true, at: 'target' }] },
    ],
  },
  {
    id: 'lucky_tail_ring',
    name: 'Lucky Tail Ring',
    description: 'Dodge in style, and the style pays you back.',
    rarity: 1,
    basePrice: 29,
    maxStacks: -1,
    tags: ['shiny', 'jungle'],
    statMods: { dodge: 2 },
    effects: [
      { trigger: 'onDodge', chance: 50, do: [{ op: 'coins', amount: 1 }] },
    ],
  },
  {
    id: 'xp_leech',
    name: 'XP Leech',
    description: 'It slurps knowledge from the fallen. Gross. Effective.',
    rarity: 1,
    basePrice: 30,
    maxStacks: -1,
    tags: ['mystic', 'cursed'],
    statMods: {},
    effects: [
      { trigger: 'onKill', chance: 20, do: [{ op: 'xp', amount: 1 }] },
    ],
  },
  {
    id: 'regen_moss',
    name: 'Regen Moss',
    description: 'Grows on you. Literally. Keeps patching the leaks.',
    rarity: 1,
    basePrice: 27,
    maxStacks: -1,
    tags: ['jungle', 'defense'],
    statMods: {},
    effects: [
      { trigger: 'interval', interval: 3, do: [{ op: 'heal', amount: 1 }] },
    ],
  },
  {
    id: 'popcorn_pouch',
    name: 'Popcorn Pouch',
    description: 'Get hit, pop corn. The kernels hold grudges.',
    rarity: 1,
    basePrice: 30,
    maxStacks: -1,
    tags: ['fruit', 'tool'],
    statMods: {},
    effects: [
      { trigger: 'onTakeDamage', chance: 50, do: [{ op: 'projectile', visual: 'kernel', damage: 5, count: 3, speed: 12, scaled: true }] },
    ],
  },
  {
    id: 'shrugging_shell',
    name: 'Shrugging Shell',
    description: 'When things get dire it shrugs a shield onto you. What a pal.',
    rarity: 1,
    basePrice: 31,
    maxStacks: 3,
    tags: ['defense', 'jungle'],
    statMods: { shieldMax: 2 },
    effects: [
      { trigger: 'onLowHp', do: [{ op: 'shield', amount: 6 }] },
    ],
  },
]);
