// APETATO enemies — ADVANCED roster (tier 3-4, budgetCost 3-6, plus one 8).
// The jungle's middle management: buffers, blinkers, and one gibbon who
// simply refuses to jog. Pure frozen data; base wave-1 values only.

function deepFreeze(obj) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (v && typeof v === 'object') deepFreeze(v);
  }
  return Object.freeze(obj);
}

export const ADVANCED_ENEMIES = deepFreeze([
  // Circles you like a rumor, pecks like a debt collector with wings.
  {
    id: 'parrot_drone',
    name: 'Parrot Drone',
    tier: 3,
    hp: 18,
    damage: 3,
    speed: 3.6,
    radius: 0.35,
    xp: 4,
    coinChance: 0.12,
    behavior: 'orbiter',
    behaviorParams: { keepDistance: 5, fireCooldown: 1.8 },
    attack: { type: 'projectile', cooldown: 1.8, projectileSpeed: 9, projDamage: 4, projVisual: 'seed_bolt' },
    budgetCost: 3,
    eliteAllowed: true,
    model: {
      base: 'drone', scale: 0.8, primary: '#d93b3b', secondary: '#3ba7d9', accent: '#ffd93b',
      parts: [
        { shape: 'sphere', size: [0.24, 0.3, 0.34], pos: [0, 0.6, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'cone', size: [0.08, 0.2, 0.08], pos: [0, 0.66, 0.3], rot: [1.4, 0, 0], color: 'accent' },
        { shape: 'box', size: [0.4, 0.04, 0.16], pos: [-0.24, 0.62, 0], rot: [0, 0, 0.5], color: 'secondary' },
        { shape: 'box', size: [0.4, 0.04, 0.16], pos: [0.24, 0.62, 0], rot: [0, 0, -0.5], color: 'secondary' },
        { shape: 'box', size: [0.06, 0.04, 0.3], pos: [0, 0.58, -0.3], rot: [0.3, 0, 0], color: 'secondary' },
      ],
      animation: 'hover',
    },
    sfxDeath: 'squawk',
  },
  // Ancient masonry with a motivational-speaker complex. Nearby mobs believe in themselves.
  {
    id: 'stone_totem',
    name: 'Stone Totem',
    tier: 3,
    hp: 30,
    damage: 0,
    speed: 0,
    radius: 0.5,
    xp: 5,
    coinChance: 0.15,
    behavior: 'totem',
    behaviorParams: { stationary: true, auraType: 'frenzy' },
    attack: { type: 'aoe', cooldown: 4.0, radius: 4.5, telegraph: 1.0 },
    budgetCost: 4,
    eliteAllowed: false,
    model: {
      base: 'totem', scale: 1.1, primary: '#8f8a7a', secondary: '#5d594d', accent: '#ff9a3b',
      parts: [
        { shape: 'box', size: [0.5, 0.4, 0.5], pos: [0, 0.2, 0], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'box', size: [0.42, 0.35, 0.42], pos: [0, 0.58, 0], rot: [0, 0.3, 0], color: 'primary' },
        { shape: 'box', size: [0.34, 0.3, 0.34], pos: [0, 0.9, 0], rot: [0, 0.6, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.07, 0.07, 0.07], pos: [-0.1, 0.92, 0.17], rot: [0, 0, 0], color: 'accent' },
        { shape: 'sphere', size: [0.07, 0.07, 0.07], pos: [0.1, 0.92, 0.17], rot: [0, 0, 0], color: 'accent' },
      ],
      animation: 'none',
    },
    sfxDeath: 'rumble',
  },
  // Someone bolted armor plates onto an ape and taught it about deadlines.
  {
    id: 'robo_ape',
    name: 'Robo Ape',
    tier: 3,
    hp: 45,
    damage: 6,
    speed: 2.1,
    radius: 0.5,
    xp: 6,
    coinChance: 0.18,
    behavior: 'chaser',
    behaviorParams: {},
    attack: { type: 'contact', cooldown: 1.0 },
    budgetCost: 4,
    eliteAllowed: true,
    model: {
      base: 'ape', scale: 1.15, primary: '#6d7a85', secondary: '#3a424a', accent: '#d93b3b',
      parts: [
        { shape: 'box', size: [0.6, 0.3, 0.35], pos: [0, 0.5, 0], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'box', size: [0.2, 0.12, 0.06], pos: [0, 0.72, 0.22], rot: [0, 0, 0], color: 'accent' },
        { shape: 'cylinder', size: [0.06, 0.2, 0.06], pos: [-0.28, 0.85, -0.05], rot: [0, 0, 0.2], color: 'primary' },
        { shape: 'sphere', size: [0.05, 0.05, 0.05], pos: [-0.3, 0.98, -0.05], rot: [0, 0, 0], color: 'accent' },
        { shape: 'box', size: [0.24, 0.1, 0.2], pos: [0, 0.1, 0.28], rot: [0, 0, 0], color: 'primary' },
      ],
      animation: 'stomp',
    },
    sfxDeath: 'clank',
  },
  // Files its taxes in a dimension you can't reach. Appears behind you, judgmentally.
  {
    id: 'shadow_ape',
    name: 'Shadow Ape',
    tier: 3,
    hp: 22,
    damage: 6,
    speed: 3.0,
    radius: 0.4,
    xp: 5,
    coinChance: 0.12,
    behavior: 'teleporter',
    behaviorParams: { blinkCooldown: 3.5, blinkRange: 6 },
    attack: { type: 'contact', cooldown: 1.0 },
    budgetCost: 4,
    eliteAllowed: true,
    model: {
      base: 'ape', scale: 1.0, primary: '#2b2438', secondary: '#443a5c', accent: '#a37bff',
      parts: [
        { shape: 'sphere', size: [0.06, 0.06, 0.06], pos: [-0.1, 0.62, 0.22], rot: [0, 0, 0], color: 'accent' },
        { shape: 'sphere', size: [0.06, 0.06, 0.06], pos: [0.1, 0.62, 0.22], rot: [0, 0, 0], color: 'accent' },
        { shape: 'cone', size: [0.1, 0.3, 0.1], pos: [-0.3, 0.2, -0.15], rot: [0.4, 0, 0.9], color: 'secondary' },
        { shape: 'cone', size: [0.1, 0.3, 0.1], pos: [0.3, 0.2, -0.15], rot: [0.4, 0, -0.9], color: 'secondary' },
      ],
      animation: 'hover',
    },
    sfxDeath: 'whoosh',
  },
  // Assembled from unclaimed coconuts. Charges first, remembers what walls are later.
  {
    id: 'coconut_golem',
    name: 'Coconut Golem',
    tier: 4,
    hp: 65,
    damage: 9,
    speed: 1.6,
    radius: 0.65,
    xp: 9,
    coinChance: 0.25,
    behavior: 'charger',
    behaviorParams: { windup: 1.0, chargeSpeed: 8, chargeDuration: 0.8 },
    attack: { type: 'contact', cooldown: 1.4 },
    budgetCost: 6,
    eliteAllowed: true,
    model: {
      base: 'golem', scale: 1.4, primary: '#6b4a2b', secondary: '#4a3520', accent: '#e8d5a8',
      parts: [
        { shape: 'sphere', size: [0.55, 0.5, 0.5], pos: [0, 0.55, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'sphere', size: [0.3, 0.3, 0.3], pos: [-0.5, 0.4, 0], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.3, 0.3, 0.3], pos: [0.5, 0.4, 0], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.26, 0.24, 0.24], pos: [0, 1.05, 0], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.05, 0.05, 0.05], pos: [-0.08, 1.08, 0.2], rot: [0, 0, 0], color: 'accent' },
        { shape: 'sphere', size: [0.05, 0.05, 0.05], pos: [0.08, 1.08, 0.2], rot: [0, 0, 0], color: 'accent' },
      ],
      animation: 'stomp',
    },
    sfxDeath: 'rumble',
  },
  // A shrub with a nursing degree. Keeps patching up things you just perforated.
  {
    id: 'root_healer',
    name: 'Root Healer',
    tier: 3,
    hp: 20,
    damage: 2,
    speed: 1.9,
    radius: 0.4,
    xp: 5,
    coinChance: 0.14,
    behavior: 'healer',
    behaviorParams: { healRadius: 4, healPerSec: 3 },
    attack: { type: 'contact', cooldown: 1.2 },
    budgetCost: 4,
    eliteAllowed: true,
    model: {
      base: 'blob', scale: 0.9, primary: '#4a7d2c', secondary: '#7a5a3b', accent: '#d6f5a3',
      parts: [
        { shape: 'sphere', size: [0.4, 0.35, 0.4], pos: [0, 0.3, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'cylinder', size: [0.05, 0.3, 0.05], pos: [-0.15, 0.65, 0], rot: [0, 0, 0.3], color: 'secondary' },
        { shape: 'cylinder', size: [0.05, 0.35, 0.05], pos: [0.12, 0.68, 0], rot: [0, 0, -0.2], color: 'secondary' },
        { shape: 'sphere', size: [0.08, 0.08, 0.08], pos: [0.14, 0.88, 0], rot: [0, 0, 0], color: 'accent' },
        { shape: 'sphere', size: [0.08, 0.08, 0.08], pos: [-0.18, 0.82, 0], rot: [0, 0, 0], color: 'accent' },
      ],
      animation: 'bob',
    },
    sfxDeath: 'snap',
  },
  // Carries a bark bubble like an umbrella salesman in monsoon season. Pop the bubble first.
  {
    id: 'bark_shielder',
    name: 'Bark Shielder',
    tier: 3,
    hp: 26,
    damage: 4,
    speed: 1.8,
    radius: 0.5,
    xp: 5,
    coinChance: 0.14,
    behavior: 'shielder',
    behaviorParams: { shieldRadius: 3.5, shieldHp: 25 },
    attack: { type: 'contact', cooldown: 1.2 },
    budgetCost: 4,
    eliteAllowed: true,
    model: {
      base: 'golem', scale: 1.0, primary: '#8a6a3b', secondary: '#5d452a', accent: '#a5d64a',
      parts: [
        { shape: 'box', size: [0.5, 0.55, 0.3], pos: [0, 0.4, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'cylinder', size: [0.3, 0.08, 0.3], pos: [0, 0.4, 0.3], rot: [1.57, 0, 0], color: 'secondary' },
        { shape: 'torus', size: [0.28, 0.04, 0.28], pos: [0, 0.4, 0.34], rot: [0, 0, 0], color: 'accent' },
        { shape: 'sphere', size: [0.18, 0.16, 0.16], pos: [0, 0.82, 0], rot: [0, 0, 0], color: 'secondary' },
      ],
      animation: 'stomp',
    },
    sfxDeath: 'snap',
  },
  // Perched somewhere rude with a straw and a grievance. The dart already left.
  {
    id: 'leaf_sniper',
    name: 'Leaf Sniper',
    tier: 4,
    hp: 16,
    damage: 2,
    speed: 2.5,
    radius: 0.35,
    xp: 6,
    coinChance: 0.16,
    behavior: 'sniper',
    behaviorParams: { keepDistance: 9, fireCooldown: 3.2 },
    attack: { type: 'projectile', cooldown: 3.2, projectileSpeed: 13, projDamage: 9, projVisual: 'thorn_dart' },
    budgetCost: 5,
    eliteAllowed: true,
    model: {
      base: 'ape', scale: 0.85, primary: '#3f6b2c', secondary: '#2a4a1c', accent: '#d93b3b',
      parts: [
        { shape: 'cone', size: [0.22, 0.14, 0.22], pos: [0, 0.75, 0], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'cylinder', size: [0.03, 0.5, 0.03], pos: [0.15, 0.55, 0.2], rot: [1.2, 0, 0], color: 'primary' },
        { shape: 'sphere', size: [0.05, 0.05, 0.05], pos: [0.15, 0.62, 0.42], rot: [0, 0, 0], color: 'accent' },
        { shape: 'box', size: [0.3, 0.04, 0.2], pos: [-0.2, 0.4, -0.1], rot: [0, 0.4, 0], color: 'secondary' },
      ],
      animation: 'bob',
    },
    sfxDeath: 'snap',
  },
  // Drank the entire espresso river. Cannot be an elite because it is already too much.
  {
    id: 'frenzy_gibbon',
    name: 'Frenzy Gibbon',
    tier: 4,
    hp: 35,
    damage: 8,
    speed: 5.4,
    radius: 0.4,
    xp: 10,
    coinChance: 0.3,
    behavior: 'chaser',
    behaviorParams: {},
    attack: { type: 'contact', cooldown: 0.6 },
    budgetCost: 8,
    eliteAllowed: false,
    model: {
      base: 'ape', scale: 1.05, primary: '#b3452b', secondary: '#7a2b1c', accent: '#ffd93b',
      parts: [
        { shape: 'sphere', size: [0.08, 0.08, 0.08], pos: [-0.1, 0.62, 0.24], rot: [0, 0, 0], color: 'accent' },
        { shape: 'sphere', size: [0.08, 0.08, 0.08], pos: [0.1, 0.62, 0.24], rot: [0, 0, 0], color: 'accent' },
        { shape: 'cylinder', size: [0.07, 0.5, 0.07], pos: [-0.35, 0.35, 0], rot: [0, 0, 0.5], color: 'secondary' },
        { shape: 'cylinder', size: [0.07, 0.5, 0.07], pos: [0.35, 0.35, 0], rot: [0, 0, -0.5], color: 'secondary' },
        { shape: 'cone', size: [0.08, 0.2, 0.08], pos: [0, 0.8, -0.05], rot: [0.2, 0, 0], color: 'primary' },
      ],
      animation: 'hop',
    },
    sfxDeath: 'screech',
  },
]);
