// APETATO enemies — BOSSES.
// Ten arena headliners (~900 hp, 2-3 phases), one 1200-hp final act, and two
// wave-10 minibosses (~300 hp) for mid-run rude awakenings. A BossDef is an
// EnemyDef plus { isBoss, phases, arenaHint }. Phases run top-down: a phase is
// active until the boss's hp fraction drops to `untilHpPct`.
// Pure frozen data; base values only, systems apply scaling.

function deepFreeze(obj) {
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (v && typeof v === 'object') deepFreeze(v);
  }
  return Object.freeze(obj);
}

export const BOSSES = deepFreeze([
  // ---- Arena bosses -------------------------------------------------------
  // Self-crowned monarch of the grove. The crown is a peel. The peel is the law.
  {
    id: 'king_peeler',
    name: 'King Peeler',
    tier: 4,
    hp: 900,
    damage: 10,
    speed: 2.2,
    radius: 1.1,
    xp: 60,
    coinChance: 1,
    behavior: 'chaser',
    behaviorParams: {},
    attack: { type: 'contact', cooldown: 1.2 },
    budgetCost: 40,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0.5, pattern: 'charge_slam', params: { windup: 1.0, chargeSpeed: 10, slamRadius: 3, slamDamage: 14 } },
      { untilHpPct: 0, pattern: 'summon_adds', params: { addId: 'banana_slime', count: 4, interval: 8 } },
    ],
    arenaHint: 'banana_grove',
    model: {
      base: 'ape', scale: 2.2, primary: '#6b4a2b', secondary: '#ffd93b', accent: '#e8d5a8',
      parts: [
        { shape: 'cone', size: [0.3, 0.35, 0.3], pos: [0, 1.0, 0], rot: [0, 0, 0.2], color: 'secondary' },
        { shape: 'sphere', size: [0.08, 0.08, 0.08], pos: [0, 1.2, 0], rot: [0, 0, 0], color: 'accent' },
        { shape: 'box', size: [0.7, 0.3, 0.4], pos: [0, 0.5, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'cone', size: [0.12, 0.4, 0.12], pos: [-0.4, 0.7, 0.1], rot: [0, 0, 0.6], color: 'secondary' },
        { shape: 'cone', size: [0.12, 0.4, 0.12], pos: [0.4, 0.7, 0.1], rot: [0, 0, -0.6], color: 'secondary' },
      ],
      animation: 'stomp',
    },
    sfxDeath: 'boss_roar',
  },
  // Runs the beach like a casino. The house always wins; the house has claws.
  {
    id: 'crab_matriarch',
    name: 'Crab Matriarch',
    tier: 4,
    hp: 900,
    damage: 9,
    speed: 1.8,
    radius: 1.2,
    xp: 60,
    coinChance: 1,
    behavior: 'chaser',
    behaviorParams: {},
    attack: { type: 'contact', cooldown: 1.3 },
    budgetCost: 40,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0.6, pattern: 'ground_pound', params: { radius: 3.5, damage: 12, telegraph: 1.0, interval: 5 } },
      { untilHpPct: 0.25, pattern: 'summon_adds', params: { addId: 'scuttle_crab', count: 5, interval: 9 } },
      { untilHpPct: 0, pattern: 'charge_slam', params: { windup: 0.8, chargeSpeed: 11, slamRadius: 3, slamDamage: 15 } },
    ],
    arenaHint: 'crab_beach',
    model: {
      base: 'crab', scale: 2.4, primary: '#d9543b', secondary: '#8a3222', accent: '#ffe8d0',
      parts: [
        { shape: 'box', size: [0.9, 0.35, 0.6], pos: [0, 0.35, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'sphere', size: [0.3, 0.26, 0.26], pos: [-0.65, 0.35, 0.3], rot: [0, 0.4, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.3, 0.26, 0.26], pos: [0.65, 0.35, 0.3], rot: [0, -0.4, 0], color: 'secondary' },
        { shape: 'cone', size: [0.1, 0.25, 0.1], pos: [-0.2, 0.65, 0], rot: [0, 0, 0.2], color: 'accent' },
        { shape: 'cone', size: [0.1, 0.25, 0.1], pos: [0.2, 0.65, 0], rot: [0, 0, -0.2], color: 'accent' },
      ],
      animation: 'stomp',
    },
    sfxDeath: 'boss_crunch',
  },
  // Long enough to be three snakes in a trench coat. Venom subscription included.
  {
    id: 'viper_empress',
    name: 'Viper Empress',
    tier: 4,
    hp: 900,
    damage: 8,
    speed: 2.6,
    radius: 1.0,
    xp: 60,
    coinChance: 1,
    behavior: 'charger',
    behaviorParams: { windup: 0.9, chargeSpeed: 12, chargeDuration: 0.7 },
    attack: { type: 'contact', cooldown: 1.1 },
    budgetCost: 40,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0.55, pattern: 'ring_barrage', params: { count: 10, projectileSpeed: 7, projDamage: 6, interval: 4, projVisual: 'venom_glob' } },
      { untilHpPct: 0.2, pattern: 'summon_adds', params: { addId: 'vine_snake', count: 4, interval: 8 } },
      { untilHpPct: 0, pattern: 'rage_spiral', params: { count: 14, projectileSpeed: 8, projDamage: 7, duration: 3, projVisual: 'venom_glob' } },
    ],
    arenaHint: 'viper_marsh',
    model: {
      base: 'snake', scale: 2.2, primary: '#4a8a3b', secondary: '#8a3ba7', accent: '#ffd93b',
      parts: [
        { shape: 'cylinder', size: [0.25, 1.2, 0.25], pos: [0, 0.3, -0.4], rot: [1.35, 0, 0], color: 'primary' },
        { shape: 'sphere', size: [0.35, 0.3, 0.4], pos: [0, 0.7, 0.4], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'cone', size: [0.1, 0.2, 0.1], pos: [-0.15, 0.95, 0.4], rot: [0, 0, 0.2], color: 'accent' },
        { shape: 'cone', size: [0.1, 0.2, 0.1], pos: [0.15, 0.95, 0.4], rot: [0, 0, -0.2], color: 'accent' },
        { shape: 'sphere', size: [0.07, 0.07, 0.07], pos: [-0.12, 0.75, 0.7], rot: [0, 0, 0], color: 'accent' },
        { shape: 'sphere', size: [0.07, 0.07, 0.07], pos: [0.12, 0.75, 0.7], rot: [0, 0, 0], color: 'accent' },
      ],
      animation: 'slither',
    },
    sfxDeath: 'boss_hiss',
  },
  // The canopy's air-traffic controller. Cleared you for an emergency landing.
  {
    id: 'sky_shrieker',
    name: 'Sky Shrieker',
    tier: 4,
    hp: 900,
    damage: 7,
    speed: 3.2,
    radius: 1.0,
    xp: 60,
    coinChance: 1,
    behavior: 'orbiter',
    behaviorParams: { keepDistance: 6, fireCooldown: 2.0 },
    attack: { type: 'projectile', cooldown: 2.0, projectileSpeed: 9, projDamage: 6, projVisual: 'feather_blade' },
    budgetCost: 40,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0.55, pattern: 'ring_barrage', params: { count: 12, projectileSpeed: 8, projDamage: 6, interval: 4, projVisual: 'feather_blade' } },
      { untilHpPct: 0.25, pattern: 'summon_adds', params: { addId: 'parrot_drone', count: 3, interval: 9 } },
      { untilHpPct: 0, pattern: 'laser_sweep', params: { sweepArc: 3.14, sweepTime: 2.5, dps: 12, telegraph: 1.0 } },
    ],
    arenaHint: 'canopy_heights',
    model: {
      base: 'drone', scale: 2.0, primary: '#d93b3b', secondary: '#3ba7d9', accent: '#ffd93b',
      parts: [
        { shape: 'sphere', size: [0.4, 0.5, 0.55], pos: [0, 0.8, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'cone', size: [0.14, 0.35, 0.14], pos: [0, 0.9, 0.5], rot: [1.4, 0, 0], color: 'accent' },
        { shape: 'box', size: [0.8, 0.06, 0.3], pos: [-0.5, 0.85, 0], rot: [0, 0, 0.4], color: 'secondary' },
        { shape: 'box', size: [0.8, 0.06, 0.3], pos: [0.5, 0.85, 0], rot: [0, 0, -0.4], color: 'secondary' },
        { shape: 'box', size: [0.1, 0.06, 0.5], pos: [0, 0.8, -0.5], rot: [0.3, 0, 0], color: 'secondary' },
        { shape: 'cone', size: [0.08, 0.25, 0.08], pos: [0, 1.25, 0], rot: [0, 0, 0.3], color: 'accent' },
      ],
      animation: 'hover',
    },
    sfxDeath: 'boss_squawk',
  },
  // Sleeps in the caldera because the jungle "wasn't warm enough". Radiates opinions.
  {
    id: 'cinder_kong',
    name: 'Cinder Kong',
    tier: 4,
    hp: 950,
    damage: 12,
    speed: 2.0,
    radius: 1.2,
    xp: 65,
    coinChance: 1,
    behavior: 'chaser',
    behaviorParams: {},
    attack: { type: 'contact', cooldown: 1.2 },
    budgetCost: 42,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0.6, pattern: 'ground_pound', params: { radius: 4, damage: 14, telegraph: 1.1, interval: 5 } },
      { untilHpPct: 0.25, pattern: 'ring_barrage', params: { count: 10, projectileSpeed: 6, projDamage: 8, interval: 4, projVisual: 'magma_glob' } },
      { untilHpPct: 0, pattern: 'rage_spiral', params: { count: 16, projectileSpeed: 7, projDamage: 8, duration: 3, projVisual: 'magma_glob' } },
    ],
    arenaHint: 'volcano_rim',
    model: {
      base: 'golem', scale: 2.4, primary: '#3a2b26', secondary: '#ff5a1f', accent: '#ffd93b',
      parts: [
        { shape: 'box', size: [0.8, 0.5, 0.5], pos: [0, 0.5, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'sphere', size: [0.35, 0.3, 0.3], pos: [0, 1.0, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'box', size: [0.3, 0.1, 0.05], pos: [0, 1.05, 0.28], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.35, 0.35, 0.35], pos: [-0.6, 0.45, 0], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.35, 0.35, 0.35], pos: [0.6, 0.45, 0], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'cone', size: [0.1, 0.3, 0.1], pos: [0, 1.3, -0.1], rot: [0, 0, 0], color: 'accent' },
      ],
      animation: 'stomp',
    },
    sfxDeath: 'boss_rumble',
  },
  // Conducts the storm like an orchestra. Every movement ends in a percussion section.
  {
    id: 'thunder_mandrill',
    name: 'Thunder Mandrill',
    tier: 4,
    hp: 900,
    damage: 9,
    speed: 2.8,
    radius: 1.0,
    xp: 60,
    coinChance: 1,
    behavior: 'teleporter',
    behaviorParams: { blinkCooldown: 4, blinkRange: 8 },
    attack: { type: 'aoe', cooldown: 3.0, radius: 3, telegraph: 0.8 },
    budgetCost: 40,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0.55, pattern: 'teleport_burst', params: { blinkRange: 8, burstCount: 8, projectileSpeed: 8, projDamage: 6, projVisual: 'spark_bolt' } },
      { untilHpPct: 0.2, pattern: 'laser_sweep', params: { sweepArc: 2.6, sweepTime: 2.0, dps: 14, telegraph: 0.9 } },
      { untilHpPct: 0, pattern: 'rage_spiral', params: { count: 12, projectileSpeed: 9, projDamage: 7, duration: 3, projVisual: 'spark_bolt' } },
    ],
    arenaHint: 'storm_plateau',
    model: {
      base: 'ape', scale: 2.0, primary: '#3a4a8a', secondary: '#7ec8e3', accent: '#fff2b0',
      parts: [
        { shape: 'cone', size: [0.12, 0.45, 0.12], pos: [-0.15, 1.05, 0], rot: [0, 0, 0.4], color: 'accent' },
        { shape: 'cone', size: [0.12, 0.5, 0.12], pos: [0.1, 1.1, 0], rot: [0, 0, -0.2], color: 'accent' },
        { shape: 'box', size: [0.6, 0.28, 0.4], pos: [0, 0.5, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'box', size: [0.24, 0.1, 0.28], pos: [0, 0.72, 0.24], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'torus', size: [0.3, 0.05, 0.3], pos: [0, 0.15, 0], rot: [1.57, 0, 0], color: 'secondary' },
      ],
      animation: 'hop',
    },
    sfxDeath: 'boss_zap',
  },
  // Four thousand years of guard duty and you're the first visitor without an appointment.
  {
    id: 'temple_guardian',
    name: 'Temple Guardian',
    tier: 4,
    hp: 950,
    damage: 11,
    speed: 1.7,
    radius: 1.3,
    xp: 65,
    coinChance: 1,
    behavior: 'charger',
    behaviorParams: { windup: 1.2, chargeSpeed: 9, chargeDuration: 0.9 },
    attack: { type: 'contact', cooldown: 1.4 },
    budgetCost: 42,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0.6, pattern: 'shield_totems', params: { totemCount: 3, totemHp: 40, shieldPct: 0.8 } },
      { untilHpPct: 0.25, pattern: 'ground_pound', params: { radius: 4.5, damage: 15, telegraph: 1.2, interval: 5 } },
      { untilHpPct: 0, pattern: 'charge_slam', params: { windup: 0.9, chargeSpeed: 11, slamRadius: 3.5, slamDamage: 16 } },
    ],
    arenaHint: 'ancient_temple',
    model: {
      base: 'golem', scale: 2.5, primary: '#8f8a7a', secondary: '#5d594d', accent: '#3bd9a7',
      parts: [
        { shape: 'box', size: [0.9, 0.6, 0.55], pos: [0, 0.55, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'box', size: [0.5, 0.4, 0.4], pos: [0, 1.1, 0], rot: [0, 0.2, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.09, 0.09, 0.09], pos: [-0.12, 1.15, 0.22], rot: [0, 0, 0], color: 'accent' },
        { shape: 'sphere', size: [0.09, 0.09, 0.09], pos: [0.12, 1.15, 0.22], rot: [0, 0, 0], color: 'accent' },
        { shape: 'box', size: [0.35, 0.5, 0.35], pos: [-0.7, 0.35, 0], rot: [0, 0, 0.1], color: 'secondary' },
        { shape: 'box', size: [0.35, 0.5, 0.35], pos: [0.7, 0.35, 0], rot: [0, 0, -0.1], color: 'secondary' },
      ],
      animation: 'stomp',
    },
    sfxDeath: 'boss_rumble',
  },
  // Retired silverback, un-retired grudge. The dark isn't empty; it's staffed.
  {
    id: 'umbral_silverback',
    name: 'Umbral Silverback',
    tier: 4,
    hp: 900,
    damage: 10,
    speed: 3.0,
    radius: 1.1,
    xp: 60,
    coinChance: 1,
    behavior: 'teleporter',
    behaviorParams: { blinkCooldown: 3, blinkRange: 9 },
    attack: { type: 'contact', cooldown: 1.0 },
    budgetCost: 40,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0.5, pattern: 'teleport_burst', params: { blinkRange: 9, burstCount: 6, projectileSpeed: 9, projDamage: 7, projVisual: 'shadow_shard' } },
      { untilHpPct: 0.2, pattern: 'summon_adds', params: { addId: 'shadow_ape', count: 3, interval: 10 } },
      { untilHpPct: 0, pattern: 'charge_slam', params: { windup: 0.7, chargeSpeed: 13, slamRadius: 3, slamDamage: 15 } },
    ],
    arenaHint: 'night_jungle',
    model: {
      base: 'ape', scale: 2.2, primary: '#1f1a2e', secondary: '#443a5c', accent: '#a37bff',
      parts: [
        { shape: 'box', size: [0.7, 0.3, 0.45], pos: [0, 0.5, 0], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.09, 0.09, 0.09], pos: [-0.12, 0.85, 0.25], rot: [0, 0, 0], color: 'accent' },
        { shape: 'sphere', size: [0.09, 0.09, 0.09], pos: [0.12, 0.85, 0.25], rot: [0, 0, 0], color: 'accent' },
        { shape: 'cone', size: [0.12, 0.4, 0.12], pos: [-0.35, 0.25, -0.2], rot: [0.4, 0, 0.9], color: 'primary' },
        { shape: 'cone', size: [0.12, 0.4, 0.12], pos: [0.35, 0.25, -0.2], rot: [0.4, 0, -0.9], color: 'primary' },
      ],
      animation: 'hover',
    },
    sfxDeath: 'boss_whoosh',
  },
  // Firmware version: vengeance. Rebooted itself out of the scrapheap for this.
  {
    id: 'apex_automaton',
    name: 'Apex Automaton',
    tier: 4,
    hp: 950,
    damage: 10,
    speed: 2.4,
    radius: 1.2,
    xp: 65,
    coinChance: 1,
    behavior: 'shooter',
    behaviorParams: { keepDistance: 7, fireCooldown: 1.6 },
    attack: { type: 'projectile', cooldown: 1.6, projectileSpeed: 10, projDamage: 7, projVisual: 'bolt_slug' },
    budgetCost: 42,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0.6, pattern: 'laser_sweep', params: { sweepArc: 3.14, sweepTime: 2.2, dps: 13, telegraph: 1.0 } },
      { untilHpPct: 0.25, pattern: 'summon_adds', params: { addId: 'robo_ape', count: 3, interval: 10 } },
      { untilHpPct: 0, pattern: 'ring_barrage', params: { count: 14, projectileSpeed: 9, projDamage: 7, interval: 3, projVisual: 'bolt_slug' } },
    ],
    arenaHint: 'robo_ruins',
    model: {
      base: 'golem', scale: 2.3, primary: '#6d7a85', secondary: '#3a424a', accent: '#d93b3b',
      parts: [
        { shape: 'box', size: [0.8, 0.55, 0.5], pos: [0, 0.55, 0], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'box', size: [0.4, 0.3, 0.35], pos: [0, 1.05, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'box', size: [0.26, 0.08, 0.05], pos: [0, 1.08, 0.2], rot: [0, 0, 0], color: 'accent' },
        { shape: 'cylinder', size: [0.08, 0.4, 0.08], pos: [-0.45, 1.0, 0], rot: [0, 0, 0.2], color: 'primary' },
        { shape: 'sphere', size: [0.07, 0.07, 0.07], pos: [-0.5, 1.25, 0], rot: [0, 0, 0], color: 'accent' },
        { shape: 'cylinder', size: [0.12, 0.35, 0.12], pos: [0.5, 0.6, 0.2], rot: [1.2, 0, 0], color: 'primary' },
      ],
      animation: 'stomp',
    },
    sfxDeath: 'boss_clank',
  },
  // The final banana-lord. Owns the throne, the jungle, and — per his lawyers — you.
  {
    id: 'gorillard_prime',
    name: 'Gorillard Prime',
    tier: 4,
    hp: 1200,
    damage: 13,
    speed: 2.4,
    radius: 1.4,
    xp: 100,
    coinChance: 1,
    behavior: 'chaser',
    behaviorParams: {},
    attack: { type: 'contact', cooldown: 1.1 },
    budgetCost: 50,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0.65, pattern: 'charge_slam', params: { windup: 0.9, chargeSpeed: 12, slamRadius: 3.5, slamDamage: 16 } },
      { untilHpPct: 0.3, pattern: 'shield_totems', params: { totemCount: 4, totemHp: 50, shieldPct: 0.85 } },
      { untilHpPct: 0, pattern: 'rage_spiral', params: { count: 18, projectileSpeed: 8, projDamage: 9, duration: 4, projVisual: 'gold_peel' } },
    ],
    arenaHint: 'gorillard_throne',
    model: {
      base: 'ape', scale: 2.8, primary: '#2b2b2b', secondary: '#ffc832', accent: '#d93b3b',
      parts: [
        { shape: 'cone', size: [0.35, 0.4, 0.35], pos: [0, 1.25, 0], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.1, 0.1, 0.1], pos: [0, 1.5, 0], rot: [0, 0, 0], color: 'accent' },
        { shape: 'box', size: [0.9, 0.4, 0.5], pos: [0, 0.55, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'box', size: [0.5, 0.14, 0.1], pos: [0, 0.8, 0.28], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.4, 0.4, 0.4], pos: [-0.7, 0.45, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'sphere', size: [0.4, 0.4, 0.4], pos: [0.7, 0.45, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'torus', size: [0.22, 0.05, 0.22], pos: [-0.7, 0.45, 0.3], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'torus', size: [0.22, 0.05, 0.22], pos: [0.7, 0.45, 0.3], rot: [0, 0, 0], color: 'secondary' },
      ],
      animation: 'stomp',
    },
    sfxDeath: 'boss_finale',
  },

  // ---- Wave-10 minibosses --------------------------------------------------
  // Middle management of the beach. Half the size of the Matriarch, twice the ego.
  {
    id: 'crab_captain',
    name: 'Crab Captain',
    tier: 4,
    hp: 300,
    damage: 7,
    speed: 2.2,
    radius: 0.8,
    xp: 25,
    coinChance: 1,
    behavior: 'chaser',
    behaviorParams: {},
    attack: { type: 'contact', cooldown: 1.1 },
    budgetCost: 20,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0.4, pattern: 'ground_pound', params: { radius: 3, damage: 10, telegraph: 0.9, interval: 5 } },
      { untilHpPct: 0, pattern: 'summon_adds', params: { addId: 'scuttle_crab', count: 3, interval: 8 } },
    ],
    arenaHint: 'crab_beach',
    model: {
      base: 'crab', scale: 1.5, primary: '#c9432b', secondary: '#7a2b1c', accent: '#ffd93b',
      parts: [
        { shape: 'box', size: [0.65, 0.28, 0.45], pos: [0, 0.3, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'sphere', size: [0.2, 0.18, 0.18], pos: [-0.48, 0.3, 0.22], rot: [0, 0.4, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.2, 0.18, 0.18], pos: [0.48, 0.3, 0.22], rot: [0, -0.4, 0], color: 'secondary' },
        { shape: 'cone', size: [0.14, 0.2, 0.14], pos: [0, 0.52, 0], rot: [0, 0, 0], color: 'accent' },
      ],
      animation: 'stomp',
    },
    sfxDeath: 'boss_crunch',
  },
  // The slime that unionized. Every hit spawns a new dues-paying member.
  {
    id: 'royal_slime',
    name: 'Royal Slime',
    tier: 4,
    hp: 300,
    damage: 6,
    speed: 1.9,
    radius: 0.9,
    xp: 25,
    coinChance: 1,
    behavior: 'splitter',
    behaviorParams: { splitInto: 'banana_slime', count: 2 },
    attack: { type: 'contact', cooldown: 1.0 },
    budgetCost: 20,
    eliteAllowed: false,
    isBoss: true,
    phases: [
      { untilHpPct: 0, pattern: 'summon_adds', params: { addId: 'banana_slimelet', count: 4, interval: 6 } },
    ],
    arenaHint: 'banana_grove',
    model: {
      base: 'blob', scale: 1.8, primary: '#ffd93b', secondary: '#c9a52b', accent: '#8a3ba7',
      parts: [
        { shape: 'sphere', size: [0.7, 0.55, 0.7], pos: [0, 0.45, 0], rot: [0, 0, 0], color: 'primary' },
        { shape: 'cone', size: [0.22, 0.25, 0.22], pos: [0, 1.0, 0], rot: [0, 0, 0], color: 'accent' },
        { shape: 'sphere', size: [0.08, 0.08, 0.08], pos: [-0.2, 0.6, 0.55], rot: [0, 0, 0], color: 'secondary' },
        { shape: 'sphere', size: [0.08, 0.08, 0.08], pos: [0.2, 0.6, 0.55], rot: [0, 0, 0], color: 'secondary' },
      ],
      animation: 'hop',
    },
    sfxDeath: 'boss_splat',
  },
]);
